### ISSUE TITLE
Look into per namespace debug levels for logback config

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/genegraph#125]

**Comment by larrybabb** [comment]
@theferrit32 can you add some additional info to clarify what this request is hoping to accomplish and how urgent it is? Is it for a specific product (genegraph, clingenvar, etc...)?

**Comment by theferrit32** [comment]
@larrybabb we want to be able to properly set up logging calls to particular log levels, and an overall log level, while also being able to selectively view deeper log levels in particularly package namespaces. Like setting `genegraph` log level to INFO, but set DEBUG log level specifically in `genegraph.source.graphql.clinvar`, avoiding editing the log calls there to INFO or the overall log level to DEBUG.

I talked to @toneillbroad today about this and will work on it.
