### ISSUE TITLE
Create a GraphQL schema and resolver for SCV v1 data

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#128]
Acceptance Criteria:
An API user can perform a GraphQL query for SCV data:

SCV Field List
- SCV ID
- Last Evaluated Date
- Interpretation (clinsig, classification) - per ClinVar
- Review Status
- Collection Method*
- Submitter (Name, Org ID, Abbreviation)
- Allele Origin*
- Date submitted
- Star level/review status
- Most current ClinVar release date

*Need to unpack these fields - defer to separate ticket if needed

**Comment by theferrit32** [comment]
Finished (except allele origin and collection method) with https://github.com/clingen-data-model/genegraph/pull/123
