### ISSUE TITLE
Specification of Dosage Sensitivity Report Fields

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#13]
Need to specify the origin or calculation for the following fields in the Dosage Sensitivity report screen:
Location relationship - what are the possible enum values. How is this field calculated?
Morbid - What are the OMIM values?
%HI Index - How is this value calculated?
Loss Intolerance (pLI) - How is this field calculated?

**Comment by toneillbroad** [comment]
Fields have been described in detail: https://github.com/clingen-data-model/website-clinicalgenome-search/wiki/Dosage-Sensitivity

**Comment by sgoehringer** [comment]
FIRST CLOSED ISSUE!  YAYA!  @toneillbroad
