### ISSUE TITLE
Update clinvar assertion transformer to annotate with classification context 

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/genegraph#134]
This is to add a new classification context field to SCVs and to load them with the proper binning terms : germline disease, somatic cancer, pharmacogenomic and other.

Accpetance Criteria:
Should be able to perform a graphql query (and display in the UI) to see which bin any given SCV is in.

**Comment by theferrit32** [comment]
If any fields related to classification context change on a variation, we need to reprocess assertions related to that variation, and store new named graphs for them if the reprocessing resulted in a change to the classification context.

Example: SCV1 originally is not considered to have the context somatic cancer because no genes linked to its variant were in the cancer genes list. But later, the variation record is updated to include a gene that is in the cancer genes list. Now the SCV1 should be annotated with the somatic cancer classification context. 

A whole new SCV1 versioned named graph should be created with a new contribution. Release date on the new SCV1 should be the same as the variation record which triggered the reclassification. (this should make it reproducible)

**Comment by theferrit32** [comment]
Now that #164 is done, somatic cancer assertion classification contexts is also done. Other classification contexts will be done shortly.

Relevant code section: 
https://github.com/clingen-data-model/genegraph/blob/be948442f289a3bc19e905ac295bb34be2c6c6fe/src/genegraph/transform/clinvar/jsonld/clinical_assertion.clj#L92-L111

**Comment by larrybabb** [comment]
@theferrit32 Question - is this transformation happening before the clinvar data is added to jena or are you essentially creating this data after the raw clinvar data has been added? we can take this offline and chat as I'd like to have a strong understanding of the processing and workflow.

**Comment by theferrit32** [comment]
Backend: https://github.com/clingen-data-model/genegraph/pull/186
Frontend: https://github.com/clingen-data-model/curator/pull/37
