### ISSUE TITLE
Improve production Genegraph Google Alerts message to be more descriptive

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#136]
The current production Google Alerts message that sends a message to #clinvar-alerts slack channel on outage/service restoration could use more descriptive text for non-engineering users subscribing to the channel.

**Comment by larrybabb** [comment]
@toneillbroad is this in your urgent bucket or todo bucket?

I'm putting it in the product backlog for now so we can keep the "new issues" lane clear for new issues that emerge.

**Comment by toneillbroad** [comment]
Due to the Google Alert configuration, I've made changes to the alert message that appears in #clinvar_alerts slack channel to be more informative. It still prints some information that google provides, but I couldn't make any changes to that information.
