### ISSUE TITLE
Improve Genegraph server logging

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#139]
Improve Genegraph server logging to include hostname, ip address, full request payload, server response status on each request.
Stream to kafka as well.

**Comment by larrybabb** [comment]
@toneillbroad could you let me know if there's been any investigation or solution planning or work on this? If not, could we ask steve jahl possibly?

**Comment by toneillbroad** [comment]
I am currently working on this. We will be logging all web requests to a kafka stream, but only in production. This would also allow for determining how long requests are taking. It will also allow for playback of requests.

**Comment by toneillbroad** [comment]
Established an interceptor (request-logging-interceptor) in the pedestal interceptor stack for logging all GraphQL servlet request information above as well as the calculated time in ms that a request takes to execute and return a result. Also enabled a kafka logback appender, that is configured in the config/logback.xml logging configuration file, to log only the output of the request-logging-interceptor to a configurable kafka stream. The intent is to log only production requests so that local dev environments don't log requests. 

Since we are using a log appender, the request-logging-interceptor logs to the genegraph output log, AND to the kafka topic when so configured.

All of that has been successfully tested against the genegraph-dev GCP environment.

However, there is a problem discovered yesterday with this (3/30/2021). 

The kafka appender is set to write request/response log messages asynchronously and without waiting for a response from kafka. The reasoning behind this is that since these are log messages, we want the process not to block waiting on ACKs from kafka and if kafka is unavailable, it is ok to drop a log message or two on the floor.

THE DEFECT: Very long requests (like retrieving all Genes, Diseases or Drugs for the first time)  are being logged to the genegraph output log but are not being logged to the kafka stream. Shorter requests are being logged to both logs. It appears that some timeout value is being breached. I will check the code and see if I am logging at the very last chance and try to determine what timeout is being breached if any.
