### ISSUE TITLE
Validity Assertion no longer there

### ISSUE THREAD

**Issue by plweller3** [clingen-data-model/genegraph#143]
can anyone tell me whats up with validity assertion CGGV:assertion_9295bddb-d61c-47c2-b186-97296b9c4d94-2021-03-22T204903.367Z ?  

It appeared, then disappeared and now when I query for it it just says null.  

Did the GCI retract it, and if so, when queried directly can we say its been retracted?

**Comment by tnavatar** [comment]
I can check—curations can be unpublished. Right now they’re simply removed when unpublished, but we can discuss whether we want to treat that differently that we are now. Because we have the history in the data exchange this is a choice we can make after the fact.

**Comment by tnavatar** [comment]
This curation was published and unpublished a few times on the 22nd and 23rd (see below). When a curation is unpublished it is removed entirely, which had happened for a span of a few hours there.

Perhaps a different behavior would be preferred, but this would be a decision to work with the stakeholders on.

```
genegraph.util.repl> (->> gv (events-with-value #"9295bddb-d61c-47c2-b186-97296b9c4d94") (map process-event-dry-run) (map ::ann/action))
(:publish :unpublish :publish :unpublish :publish)
genegraph.util.repl> (->> gv (events-with-value #"9295bddb-d61c-47c2-b186-97296b9c4d94") (map #(-> % ::stream/timestamp Instant/ofEpochMilli)))
(#object[java.time.Instant 0x2a26c0f8 "2021-03-22T20:49:16.111Z"]
 #object[java.time.Instant 0x7a21a02e "2021-03-23T13:25:35.645Z"]
 #object[java.time.Instant 0x1504d345 "2021-03-23T17:53:53.511Z"]
 #object[java.time.Instant 0x2bd01a54 "2021-03-23T18:49:16.377Z"]
 #object[java.time.Instant 0x7e269949 "2021-03-23T18:50:01.919Z"])
```

**Comment by tnavatar** [comment]
@plweller3 @larrybabb See answer above, happy to respond to any additional questions. Moving to review for now.
