### ISSUE TITLE
Request for Explanation on why Dosage curation CURIEs get modified on updates even though resolution dates don't change.

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#144]
When an update is made to a curation, even if it has no impact on the resolution date, it triggers a new curie in Genegraph.

It is not clear whether this is intended or a holdover from the days when an update changed the resolution date.

Would like to understand better the conditions by which a new curie would be assigned to a curation, versus a record update while maintaining the same curie and resolution information.

The genegraph group suggested opening a ticket here.  I'm listing it as a bug, only because there is no issue type for RFI.

**Comment by larrybabb** [comment]
@tnavatar could you follow up with @plweller3. He is asking for an RFI (which I believe is a request for information). He needs to be edified on how updates to curations impact resolution dates and thus cause new curies to be generated in genegraph.

He believes it may be an outdated issue that should have been modified when in the past the update caused the resolution date to change.

He's looking for a document or explanation (prefer the documented answer be listed in this thread for future reference) on when curies change based on updates (essentially).

You may need to get more clarity on specifically what he wants beyond that so that this does not become a very large request. But please satisfy his immediate concerns as it is important for him to understand the behavior as he is depending on it for behaviors in his downstream process.

I believe this is focused primarily on Dosage related data, but if there is some systemic notion or pattern that bleeds over into other areas that would also impact curie modifications then please clear that up and document below.

Thanks, Larry

**Comment by tnavatar** [comment]
@larrybabb @plweller3 

The updated data is currently used for Dosage IRIs and not the resolution. I would prefer this to remain the case as it maintains the property that dosage curations are immutable, but we can discuss use cases that might be impeded by this.
