### ISSUE TITLE
curation removal request (legacy GDV assertion_8772)

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#146]
From @sgoehringer to @tnavatar within Jira ticket [#CGWM-234](https://broadinstitute.atlassian.net/browse/CGWM-234) conversation thread.
The curation was removed from the JSON file. Please grab this issue when you can and release the update
https://github.com/clingen-data-model/data-exchange-shared-json/commit/800c1c4bde35d5a92deb14e10bcfb98883d0882e - Connect to preview

**Comment by tnavatar** [comment]
This will be removed with the next Genegraph build, expected in the next couple days.

**Comment by tnavatar** [comment]
This update has been released to prod
