### ISSUE TITLE
MONDO terms not showing up on list view of dosage curations

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#147]
Moved from Jira [#CGWM-233](https://broadinstitute.atlassian.net/browse/CGWM-233)

We recently closed two dosage curations that have MONDO terms associated with them. The terms are showing up on the detailed view of the dosage curation but not the list view. The two curation links are listed below:
https://search.clinicalgenome.org/kb/genes/HGNC:3811
https://search.clinicalgenome.org/kb/genes/HGNC:17021

(from @plweller3) @tnavatar I believe this is because genegraph does not yet support that alternative ontologies out of Jira, correct?  Maybe supporting at least Mondo for would be a fairly easy lift?

(from @tnavatar) @plweller3 It is, and it is. Erin Riggs Given that this is a pretty easy lift, would it be worth taking a moment to get this done right now?

(from ERiggs) Yes please!  That work will help pave the way for our eventual transfer over to MONDO I imagine, so it would be worth it.

**Comment by larrybabb** [comment]
@tnavatar is this in progress? if not please move back to Product Backlog.

**Comment by tnavatar** [comment]
This is in progress, anticipated completion in the next couple days.

**Comment by larrybabb** [comment]
Requested confirmation from website team that this issue resolved their original request. While awaiting confirmation we will move this to Done.
