### ISSUE TITLE
'Disease' broken for Gene Dosage curations

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#148]
Moved genegraph work from Jira ticket [#CGWM-224](https://broadinstitute.atlassian.net/browse/CGWM-224)

---
Via Phil:

??The layout for the dosage information out of genegraph is awkward.  I believe part of it was because, not so long ago, dosage allowed multiple diseases for both loss and gain.  Erin has made it clear that only one disease is allowed for each.  I believe that really​ simplifies the graphql structure.  I believe if the disease field was fully implemented - it is already there, it just returns null - it could look like this:

{genes(limit: 200, curation_activity: GENE_DOSAGE) {countgene_list {hgnc_idcuration_activitiesdosage_curation {triplosensitivity_assertion {report_datedisease {labelcurie}dosage_classification {ordinal}}haploinsufficiency_assertion {report_datedisease {labelcurie}dosage_classification {ordinal}}}}}

If there is no disease for loss or gain, it would still be null.  But if there is, it would be populated.  With this simple addition, I could eliminate a bunch of ugly parsing I have to do to find out which score is tied to a genetic condition and which applies to the entire gene.  In other words, I would not even need to make the genetic_conditions call!

On a scale of 1 - 4 (with 4 the highest priority), I would rate this a 4 for backend improvements.??

On investigation, the 'disease' field for Dosage records has been broken since the MONDO schema change some time ago. This slipped by because this field wasn't being used until Phil tried using it last week. This should be an easy enough fix and it sounds like it will make life easier for Phil.

**Comment by tnavatar** [comment]
This was completed and later reopened by @plweller3. At the time I was unable to recreate or observe the issues experienced. @larrybabb, would you be able to check in and see if this is still an issue, and if so to clarify what the problem currently is?

**Comment by tnavatar** [comment]
NVM, taking this one back--am seeing some issues.

**Comment by sgoehringer** [comment]
@larrybabb Is something ready to review?  Tristan's last comment was he was taking it back and still working on it

**Comment by plweller3** [comment]
This (or something else in the past few days) seems to have broken the disease listing under genetic_conditions.  I have updated the original ticket CGWM-224 with all the necessary information.

**Comment by larrybabb** [comment]
@Tristan know that you have rolled back the "null" vs "disease" change caused by the release of the #147 MONDO ticket in the recent release. Could you please let @sgoehringer and @plweller3 know when they can review the new release to allow all the associated requests with the last release to be re-deployed?  I'm assuming you will notify them on the #ops-u41 slack channel.

**Comment by larrybabb** [comment]
Awaiting confirmation from the website team that we have resolved their request. For now moving into Done. Will reopen if we get any followup that references any unfinished concerns related to the original ticket.
