### ISSUE TITLE
Removal request for Gene Express Curation 9616 and 9540

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#149]
From Scott G on Jira Ticket [CGWM-240](https://broadinstitute.atlassian.net/browse/CGWM-240) 
----
The JSON was updated to have the curations removed (see below)
https://github.com/clingen-data-model/data-exchange-shared-json/commit/fedc96b182608255553cd2afd6936759778c8cde

--- original request
From Stakeholder (Jenny G)

There are two gene curations that we would like to take down from the website; both are for the gene RPE65, curated by Mass Eye and Ear.https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_9616https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_9540

Matt transferred these to the Retina GCEP affiliation in the GCI, because that group wants to update them. As they do not meet current lumping and splitting guidelines, the Retina GCEP wants to take them down until we have time to update them. However, it looks like these were submitted to the website via the Gene Curation Express and not the GCI, so I cannot "unpublish" them. Please can you remove these from the website?

**Comment by larrybabb** [comment]
@tnavatar please acknowledge receipt of this request and annotate in the original jira ticket above when you will release the json changes @sgoehringer has made to remove them.

**Comment by tnavatar** [comment]
As with the prior one this will be released with the next Genegraph build

**Comment by tnavatar** [comment]
The update has been released to prod
