### ISSUE TITLE
AC1018 Not Posting to Website

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#155]
Hi Erin,
I’m guessing this is a website issue, but I’m also cc’ing Neethu just in case.
The AC1018 (prelingual non-syndromic hearing loss and deafness) report is not posting to the website. This report is different because there are 31 genes in a single report, I’m mentioning that just in case it’s a factor. Can someone make sure this report posts properly?
I think it was released on Friday, but my understanding there is not supposed to be a lag time between releasing reports and it showing up on the website.
![image.png](https://images.zenhubusercontent.com/5ff32d49cb7d78fcfb425bd8/a208a495-86dc-4fa8-8527-6922a366a81f)

**Comment by tnavatar** [comment]
https://search.clingen.info/kb/genes/HGNC:1385

**Comment by sgoehringer** [comment]
@tnavatar I can see it showing now... it wasn't last night during the demo.  Was this what you said you were working on?

**Comment by tnavatar** [comment]
Among other things, yes.  FWIW I did see it up after I updated Genegraph stage ~2PM.

**Comment by sgoehringer** [comment]
@tnavatar interesting... my call with her at 6pm yesterday didn't have it work for ESPN and another (I don't recall).  Would that have been a sticky cache for gene data?  No action item, just sharing... thanks for the update.  Let me know if/when goes out to production so I can confirm and close on our board

**Comment by tnavatar** [comment]
Update has been deployed on prod.

**Comment by larrybabb** [comment]
Update - this has been temporarily rolled back due to an unrelated change that caused unexpected display changes in dosage. 

It will be re-deployed to prod in the next quick release which is tenatively planned for this evening.

**Comment by larrybabb** [comment]
For the record - capturing a trailing but related email request from CJenkins
---

Ok, thank you! I appreciate your help!

Any idea why there are issues with this report but not any others? Is it the number of genes on one report? I don’t think we’ve had a single report with this many genes before.

---
Tristan responde on 3/31/21 at 11a ET with....
I don't think it's the number of genes. Is it possible that this curation has a relatively novel MONDO term in it? I honestly haven't dug into this too much; I just noticed that it was working fine on our most recent development builds, so my priority has been to get that into production shape for deployment, with the expectation that this issue would be fixed alongside.
