### ISSUE TITLE
Ingest & provide access to the beta release of GCI data to the Web team

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#156]
Goal: shortest path to getting real data in GraphQL and the Admin interface so that it un-gates @plweller3 and @sgoehringer from starting their implementation work on the website. 

**Acceptance**: see [genegraph#167](https://app.zenhub.com/workspace/o/clingen-data-model/genegraph/issues/167)

beta includes...

Only records that have been published since the website refactor.
Some elements of the Gene Validity are not included in this "beta" representation.
- this will include evidence item score and descriptions primarily.
- no variant, allele origin or evidence summary text in the beta version, but planned for MVP version
- future versions beyond MVP will include: additional structured info on evidence items.

This will NOT incorporate records prior to the rearchitecture. (see)
This also does not include full validation.  (see)

**Comment by dazzariti** [comment]
@tnavatar will break this ticket up into multiple discrete steps

**Comment by dazzariti** [comment]
Discussing with Gene Curation stakeholders on May 10th
