### ISSUE TITLE
Incorporate all GCI data prior to re-architecture

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#159]
As part of the epic this will be the task needed to incorporate a complete record of the GCI data in the new Full Gene Val v1 format which is required before the website can release to production.

Goal:
Transfrom all pre-refacoring release of website GCI data into GeneGraph's new form
Verify all data is available.

**Comment by larrybabb** [comment]
@tnavatar can you also tell me if/where this belongs in the plans for this epic?

**Comment by tnavatar** [comment]
At this point the prior-to-rearchitecture data is incorporated and looks good, except for the issue noted in #244 Recommend closing this ticket and keeping #244, as it has more detail on what's actually needed.
