### ISSUE TITLE
Update labels for ACI rule outs (Insufficient Evidence)

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#160]
Copied from [CGWM-256](https://broadinstitute.atlassian.net/browse/CGWM-256) Jira Ticket

Actionability seeking to have "N/A" re-introduced in assertion label for both assertions beginning with "N/A - Insufficient Evidence: ..."  

During a review with the Charisma it was requested that the "N/A -" not be removed before it is displayed.  I believe this is being removed/trimmed by GeneGraph.  

Requested Actions - 
- Please confirm that this is where the removal is made.
- Please confirm that no action is needed by Actionability to republish these
- Please don't release this update until confirming the items above
- Please don't release this update until the website April release is available (it is not expect that these updates need to happen at the 'exact' same time)

**Comment by larrybabb** [comment]
@tnavatar can we quickly chat about this?

**Comment by tnavatar** [comment]
Sure thing, free now

**Comment by larrybabb** [comment]
@tnavatar I'm sorry I forgot what the plan is for this?

I think right now all Scott wants you to do is verify whether genegraph is removing the "N/A - ..." is being removed by gengraph.
so that he can 
1. affirm that this would be isolated to a GeneGraph only change.
2. if not then he will need to go to the ACI team to fix.

**Comment by tnavatar** [comment]
Two questions: 

1) what is the intended behavior?
2) is the website using the labels from Genegraph for actionability assertions?

**Comment by tnavatar** [comment]
@larrybabb Passing this one to you for clarification. Happy to take this back when the purpose and scope is known.

**Comment by tnavatar** [comment]
I think this is part of the story key, an older message from Slack from Neethu:

> Neethu Shah  4:53 PM
> @Tristan Nelson - these are the two new values for the assertions that will be available in the upcoming release of ACI.
> N/A - Insufficient evidence: expert review
> N/A - Insufficient evidence: early rule-out
> In the current release these are represented as the following respectively :
> No Actionability
> Insufficient evidence: early rule-out

Based on this I would recommend the following course of action:

1) Confirm with Neethu and Charisma that these are the labels for these terms
2) Confirm with Neethu that this is the exact text that will be sent from the ACI for these assertions.

I think I was confused by this request--we aren't re-introducing N/A, this is new functionality, albeit a small change.

If the answer to the above is yes, we will

1) Change the labels for these concepts in SEPIO to match what the stakeholders intend.
2) Update the mapping from the text provided by the ACI to SEPIO terms to reflect the new text.

Browsing the actionability assertions, I'm not seeing any that have either the old or the new text included; it's not clear to me how urgent this is on that basis, but this will probably not remain the case forever.

**Comment by larrybabb** [comment]
@Tristan is reaching out to Neethu to clarify where the label is being re-labeled (if at all) and determining the best place in the architecture to standardize the label is presented to the website and downstream systems in a manner that is consistent with the requirements of the ACI stakeholders.

**Comment by larrybabb** [comment]
Tristan reached out to Neethu on the #aci-dx slack channel [here](https://clingen.slack.com/archives/CDQUXRUS1/p1617652031002900).

Here's the excerpts from the April 05, 2021 thread...

> Tristan Nelson  3:47 PM
Hi all, was just reviewing the labels for assertions in the ACI and the labels for these in SEPIO and Genegraph and wanted to make sure we were on the same page with everything. I've tried to represent what I think is desired in this spreadsheet: https://docs.google.com/spreadsheets/d/1KffZDJPJfXRVDZW6XHBbKxxuoueVSrogLeQpiA91j5g/edit?usp=sharing Please review as you get the chance @Charisma Jenkins @Neethu Shah. If everything looks good I'll make sure the SEPIO labels are representing what you expect and that the mappings from the ACI terms are set up appropriately. Happy to hop on a call to discuss or to answer any questions here as need be.


> Neethu Shah  3:56 PM
@Tristan Nelson, yes, the assertion labels are current and accurate.

> Charisma Jenkins  4:00 PM
I am on vacation this week, but I agree with Neethu. I do think “No Actionability” should be deleted
4:01
@Neethu Shah do you agree?

> Neethu Shah  4:24 PM
Yes, I concur. No Actionability is no longer in use and is obsolete.
:+1:
1

**Comment by larrybabb** [comment]
@tnavatar please do not release this fix without first coordinating it with @sgoehringer.

**Comment by larrybabb** [comment]
@larrybabb follow up with Scott to see when he's ready for this.
