### ISSUE TITLE
Dosage data shows false "disease-no evidence" curations.

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#162]
@plweller3 noticed at 7:16a this morning that the production (and stage) websites were showing errant curation entries when none existed. They all show "Disease MONDO:0000001" and "No Evidence" for either/both the triplo/haplo scores. The latest release of GG seems to be returning these false records.

![image.png](https://images.zenhubusercontent.com/5ff32d49cb7d78fcfb425bd8/bdf0b5ce-05e6-4ad3-8c7d-37c984e82770)

**Comment by tnavatar** [comment]
Change is being rolled back on prod currently. A fix for this exists in PR 153

**Comment by larrybabb** [comment]
[Instigating Text](https://clingen.slack.com/archives/GHEB7MZHQ/p1617275783004100) on the slack #ops-u41 channel
---
Phillip Weller  7:16 AM
@Tristan Nelson @Larry Babb @Scott Goehringer We have a problem on production.  I was reviewing the changes to dosage disease on stage and noticed a problem.  But that problem is also showing up on production!!  Look at the dosage entry for gene ATP7A.  Near as I can tell, this is happening for EVERY dosage gene that has no disease for haplo or triplo, which is over 1000 of them.  I think whatever update was done needs to be rolled back ASAP from production.

**Comment by tnavatar** [comment]
The fix for this issue has been deployed to production.
