### ISSUE TITLE
Link clinvar variations to genes

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/genegraph#164]
The clinvar data has a `gene_association` table linking `variation` to `gene`. In theory these could be rolled up into variation, but that would result in duplication of the genes so isn't the best way. `gene_association` could be rolled up into `variation`.

Acceptance:
Verify by doing a graphql query for VCV and see the associated genes.

**Comment by theferrit32** [comment]
This connection and exposure through graphql as of this revision:

https://github.com/clingen-data-model/genegraph/tree/115a1af7132365e934ec115cfa37293780e9e930

Can be validated with a [graphql query](https://genegraph-dev.clingen.app/ide?query=%0A%7B%0A%20%20aggregate_assertions(subject%3A%22https%3A%2F%2Fidentifiers.org%2Fclinvar%3A12610%22%2C%20timeframe%3A%22ALL%22)%20%7B%0A%20%20%20%20iri%0A%20%20%20%20id%0A%20%20%20%20subject%20%7Bname%7D%0A%20%20%20%20predicate%0A%20%20%20%20object%0A%20%20%20%20review_status%0A%20%20%20%20release_date%0A%20%20%20%20members%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20subject%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20genes%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20predicate%0A%20%20%20%20%20%20object%0A%20%20%20%20%20%20review_status%0A%20%20%20%20%20%20allele_origins%0A%20%20%20%20%20%20collection_methods%0A%20%20%20%20%20%20version%0A%20%20%20%20%20%20contribution%20%7B%0A%20%20%20%20%20%20%20%20activity_date%0A%20%20%20%20%20%20%20%20agent%0A%20%20%20%20%20%20%20%20agent_role%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) from a Docker image built locally and deployed to dev kubernetes

**Comment by larrybabb** [comment]
@theferrit32 Looks good. I see the connection. I was expecting to see the variation iri in the Variant object. But I suppose we can add that later. Good job.

If you have no other items to satisfy for this, feel free to put it in the "Done" column

**Comment by theferrit32** [comment]
@larrybabb Thanks for pointing that out, I just updated the graphql layer to add the `iri` (versioned) and `id` (unversioned) to the variant objects

[updated query link](https://genegraph-dev.clingen.app/ide?query=%0A%7B%0A%20%20aggregate_assertions(subject%3A%22https%3A%2F%2Fidentifiers.org%2Fclinvar%3A12610%22%2C%20timeframe%3A%22LATEST%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20subject%20%7B%0A%20%20%20%20%20%20iri%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%20%20predicate%0A%20%20%20%20object%0A%20%20%20%20review_status%0A%20%20%20%20release_date%0A%20%20%20%20members%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20subject%20%7B%0A%20%20%20%20%20%20%20%20iri%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20genes%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20symbol%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20predicate%0A%20%20%20%20%20%20object%0A%20%20%20%20%20%20review_status%0A%20%20%20%20%20%20allele_origins%0A%20%20%20%20%20%20collection_methods%0A%20%20%20%20%20%20version%0A%20%20%20%20%20%20contribution%20%7B%0A%20%20%20%20%20%20%20%20activity_date%0A%20%20%20%20%20%20%20%20agent%0A%20%20%20%20%20%20%20%20agent_role%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)
