### ISSUE TITLE
As a user, I can access the ClinVar VCV level data with the SCV list through GraphQL

### ISSUE THREAD

**Issue by dazzariti** [clingen-data-model/genegraph#165]
Acceptance Criteria: Access GraphQL, enter variation ID, and see VCV level data, as well as SCVs associated with that variation ID

 

VCV Field List
Variation ID

Overall review status

VCV preferred label

Gene(s) name

If multiple, show first three gene names, if more than three (… # of genes)

 

VCV Field list in requirements doc: https://docs.google.com/document/d/1Npxnwi2J85qE9nMry8jdeOV1H-wVMLHaMc12HUdXN78/edit?usp=sharing - Connect to preview

**Comment by dazzariti** [comment]
Currently works for the most recent version of the VCV, does not yet work to query older versions of the VCV

**Comment by theferrit32** [comment]
Latest vcv version implemented in https://github.com/clingen-data-model/genegraph/pull/154

**Comment by dazzariti** [comment]
@theferrit32 Create a linked ticket finishing up this work and one for the Gene Names

**Comment by theferrit32** [comment]
New ticket to handle past versions as well: https://github.com/clingen-data-model/genegraph/issues/151

**Comment by theferrit32** [comment]
Ticket to handle linking to https://github.com/clingen-data-model/genegraph/issues/164
