### ISSUE TITLE
Create aggregate binning summary graphql endpoint.

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#166]

**Comment by theferrit32** [comment]
**Acceptance Criteria:**
Developers will provide a list of SCVs in a UI that exercise all the Classification Context binning rules and produce a report, stakeholders will use the report to validate the rules

Example -
Classification Context:
Germline = List of SCVs
Somatic = List of SCVs
Pharmacogenomic = List of SCVs
Other - List of SCVs

ClinVar Data:
Germline “Allele Origin” and Pathogenic “clin sig” = List of SCVs
Germline “Allele Origin” and Likely Pathogenic “clin sig” = List of SCVs

**Comment by larrybabb** [comment]
Not clear if this is needed or completed. Archiving
