### ISSUE TITLE
Stand up GG instance on dev for early access to MVP of full GCI

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#167]
Implement deployment using Terraform approach currently in progress with Kyle and Stephen on the clinvar project.

Acceptance:

- the admin ui is able to search on genes and return the full GCI v1 data via graphQL for any gci records since the refactor on the dev instance with. https://gci-dev.clingen.app.  pointing to genegraph instance at https://gengraph-gci-dev. 

NOTE: we are in a fairly volatile mode with the genegraph data at this time which is why we are separating the data into a genegarph-gci-dev instance temporarily.

**Comment by tnavatar** [comment]
Genegraph instance specifically targeting the new gene-validity info has been stood up:

genegraph-gvdev.clingen.app

Used Terraform to configure the cloud resources related to this.

Have split off a version of curator targeting this instance, deployed at:

genegraph-ui-dev.clingen.app

There's still a fair bit to do--especially in getting all the data present and visible, but this should satisfy this ticket.
