### ISSUE TITLE
Ingest & provide access to remaining evidence summary report MVP GCI data

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#171]
(required for MVP)
evidence summary (report level)
allele origin (evidence line/variant)

---
(optional not for MVP - waiting on stakeholder to prioritize)
sex, 
age, 
ethnicity, 
pheno, 
seg data, 
sequencing, 
prev testing, 
methods of detection

**Comment by tnavatar** [comment]
This is closable based on the progress made in last PR
