### ISSUE TITLE
Improve discovery and display of Gene Validity Assertions in Genegraph UI

### ISSUE THREAD

**Issue by tnavatar** [clingen-data-model/genegraph#178]
In our last meeting with Erin, she had mentioned that the other gene curators would like to review the data being shown in the new Gene Validity display. They will likely change the language in their curations as a result; this process will take some time to complete. Six months has been proposed as a realistic timeframe. The sooner we can get this moving, the sooner the full Gene Validity display can be released--this is therefore a major gating issue.

This will require a UI that makes it easy for curators to find their curations and browse the associated data. Having this UI will also make it easy to check some of this data in development. This part of the work is therefore a high priority.

**Acceptance Criteria**:

Users will be able to find Gene Validity curations in the following ways:

* By searching for a specific gene
* Paging through a list of all gene validity curations
* Paging through a list of gene validity curations specific to an affiliation

Once on a page, users should be able to view all evidence items associated with a given curation, especially the justification for any modification in scoring.

**Comment by larrybabb** [comment]
@tnavatar should we make this an Epic and pull out the 3 search/filter features you bulleted above as well as the "all evidence items per curation" view? I'd like to see you knock these things out one at a time if possible. Unless you think all of this fits into a single sprint.

**Comment by tnavatar** [comment]
Quite possibly; I’m doing some design work right now related to this. Can update when I have a firmer plan, but I wanted to get this in here now so that there’s a pointer for what I’m working on.

**Comment by tnavatar** [comment]
Considered closed with PR #1 on genegraph-ui; future improvements will be scoped to fit within new tickets.
