### ISSUE TITLE
Integrate germline disease clinsig normalization table

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/genegraph#180]
There are a significant number of synonymous clinical significance (interpretation description) terms that need to be mapped to the standardized terms in order for us to interpret them. 

@larrybabb created a table of those mappings that needs to be integrated into the codebase. Could either be integrated as a plain file for use in-memory in clojure code, or transformed into RDF and ingested into jena so it could be used directly in sparql queries.

**Comment by larrybabb** [comment]
There will likely be new ones introduced going forward. In fact, you should take care to identify when a new unmapped term is identified and find a way to alert or log an exception that we can then go back and rectify. Let me know if you'd like to discuss.

**Comment by theferrit32** [comment]
Initial version added in #186 

Tracking unrecognized/problematic terms with alerts should be added. We will also need to design how we manage edits, i.e. when and unrecognized term is seen, how that record is repaired. We previously discussed having a `clinvar-overrides` topic that will store manual changes to the dataset, that will be read in alongside the `clinvar-combined` topic.
