### ISSUE TITLE
Implement CvC VCV aggregation

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/genegraph#185]
This should be done on ingest of the `clinvar-combined` stream. Because individual clinical assertions (SCVs) are *always* ingested before aggregate assertions (VCVs) within a single release because of how the upstream process orders the messages, the re-aggregation of a VCV into split aggregate assertions for each classification context can be done whenever a `variation_archive` message is received, and selecting the non-deleted most recent versions of any SCV that is a member of that variation archive.

Contribution field should probably mirror the upstream release date in the message, not be the date the record was physically created by the transformer. The contribution agent should be set to `clingen`, or something similar. Using the same release date of the upstream VCV record will ensure a consistent `release_date` ordering in sparql queries, particularly after genegraph data is reloaded from upstream data.

**Comment by KelseaChang5** [comment]
December 7th 2021 Triage: Renamed from _Generate restructured aggregate clinical assertions based on ClinGen aggregation rules for ClinVar SCVs_ to _Implement CvC VCV aggregation_
