### ISSUE TITLE
Minimize migration job execution time

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#187]
Plan is to have Argo automatically deploy to stage cluster on pull request merge to master branch in the Architecture project. Ideally, a new migration would run and deploy every time there is a new Argo deploy so that there is parity and traceability with each deploy between the genegraph container image and the migration version.

This ticket is to evaluate the execution time of the migration job as it currently stands (particularly the suggester creation step) with the intent of reducing the execution time as much as possible.

**Comment by dazzariti** [comment]
@toneillbroad Base Data > Data Stream Processing > Resolvers > Suggesters, potentially create a task for each and make this ticket and Epic
