### ISSUE TITLE
Resolvers for gene validity assertion should expire on update

### ISSUE THREAD

**Issue by tnavatar** [clingen-data-model/genegraph#196]
Originally, it was not anticipated that fundamental facts about an assertion (such as the classification) would change within the same version. Since then it was discovered that curators occasionally make mistakes and would like to correct them without updating the related dates. Therefore these fields should be updated to expire whenever the associated curation is updated.

**Comment by larrybabb** [comment]
That's sort of scary. They can change previously released data? seems wrong. At the very least we should have some "minor" version tag to not loose audit-ability of publicly shared data. Unless of course we don't have a requirement to allow folks to reference the data in a reliably immutable manner.

**Comment by larrybabb** [comment]
Especially when something as significant as the "predicate" changes. I mean - come on folks.

**Comment by tnavatar** [comment]
I agree on all counts. Right now there’s no requirement as you mention, but this is really something we should talk through with the stakeholders.

For now I think we gotta do something about this though

**Comment by KelseaChang5** [comment]
December 7th 2021 Triage: Closed
