### ISSUE TITLE
Remove AP1S2 and non-syndromic X-linked intellectual disability Gene Express curation

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#199]
Could you please remove this curation from the website for AP1S2 and non-syndromic X-linked intellectual disability? I believe this is a gene curation express curation and I will be publishing a different curation from the GCI shortly. URL is below.

https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_9509

@tnavatar or @toneillbroad Scott G has already removed the gene express record from the website's gene express json file. 

Please update this and let Scott know when he can verify on Stage before deploying to Production.

see [CGWM-279](https://broadinstitute.atlassian.net/browse/CGWM-279) for original request.

**Comment by toneillbroad** [comment]
Populated gs://genegraph-dev with new file and ran a migration to produce version "2021-05-05T1915". 
Copied that version to gs://genegraph-stage and deployed.
Will message @sgoehringer to test.
