### ISSUE TITLE
Incorrect/Invalid Actionability data returned from GeneGraph via GraphQL!

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#202]
@Terry O'Neill @Tristan Nelson I traced down the bad actionability data genegraph is sending.  I’ve included a snipit of the graphql output below.  Please let me know what the issue is and how quickly we can correct, as it has been disrupting both follow-genes and reports since last thursday.  Thanks!

```
{“label”: “LDLR”,“hgnc_id”: “HGNC:6547",
   “genetic_conditions”: [{
        “actionability_assertions”: [{
            “report_date”: “2020-08-03T00:00:00Z”,
            “ source”: “https://actionability.clinicalgenome.org/ac/Adult/ui/stg2SummaryRpt?doc=AC065”,
            “attributed_to”: {“label”: “Adult Actionability Working Group”}
        },{
            “report_date”: “2020-08-03T00:00:00Z”,
            “source”: “https://actionability.clinicalgenome.org/ac/Pediatric/ui/stg2SummaryRpt?doc=AC065”,
            “attributed_to”: null
        },{
            “report_date”: “2020-08-03T00:00:00Z”,
            “source”: “https://actionability.clinicalgenome.org/ac/Adult/ui/stg2SummaryRpt?doc=AC057”,
            “attributed_to”: {“label”: “Adult Actionability Working Group”}
        },{
            “report_date”: “2020-08-03T00:00:00Z”,
            “source”: “https://actionability.clinicalgenome.org/ac/Pediatric/ui/stg2SummaryRpt?doc=AC057”,
            “attributed_to”: null
        }]
},{
```

**Comment by larrybabb** [comment]
@toneillbroad can you make this a priority to investigate and get some feedback to me and Scott as to what the issue is and when can a fix be expected?  @tnavatar is on the move possibly so he may not be available.

**Comment by larrybabb** [comment]
Just a guess here, but it looks like this is related to the Pediatric Actionability WG's affiliation record. For some reason whenever there's a pediatric actionability wg associated record it returns "null" for the "attributed to" attribute and the website is not able to handle the "null" so No results are rendered in the UI. 
To be fair the is a reasonable expectation that all curated records will have the "attributed to" value.

**Comment by toneillbroad** [comment]
This is an interim note to track how to reproduce this because it IS happening on production GraphQL, but not on stage GraphQL currently. And at first I was able to reproduce the problem on my local system, but then as I was diving into the issue I could no longer reproduce. 

Ultimately this feels like a caching issue.

To reproduce in a local dev environment:
- Use a fresh download of data-version "2021-04-21T1250".
- run with both response cache and resolver caching enabled
- run with kafka streams active (not just "run-dev")

Here is my environment:

{:genegraph-response-cache "true", :genegraph-data-version "2021-04-21T1250", :dx-topics "gene-dosage-jira;actionability;gci-legacy", :graphql-logging-topic nil, :genegraph-validate-events false, :data-vol "/Users/toneill/dev/git/genegraph/data/2021-04-21T1250", :genegraph-version nil, :genegraph-mode "production", :genegraph-bucket "genegraph-dev", :genegraph-gql-cache "true"}

Start via (mount.core/start)

Run this query:
{
  genes(limit: null, curation_activity: ACTIONABILITY) {
    gene_list{
      label
      hgnc_id
      genetic_conditions {
        disease {
          label
          curie
        }
        mode_of_inheritance {
          label
          website_display_label
          curie
          }
        actionability_assertions {
          report_date
          source
          attributed_to {
            label
          }
          classification {
            label
            curie
          }
        }
      }
    }
  }
}

Search in the graphIQL right side pane for "LDLR" and you will see:

        {
          "label": "LDLR",
          "hgnc_id": "HGNC:6547",
          "genetic_conditions": [
            {
              "disease": {
                "label": "hypercholesterolemia, familial, 1",
                "curie": "MONDO:0007750"
              },
              "mode_of_inheritance": null,
              "actionability_assertions": [
                {
                  "report_date": "2020-08-03T00:00:00Z",
                  "source": "https://actionability.clinicalgenome.org/ac/Adult/ui/stg2SummaryRpt?doc=AC065",
                  "attributed_to": {
                    "label": "Adult Actionability Working Group"
                  },
                  "classification": {
                    "label": "Assertion Pending",
                    "curie": "SEPIO:0003541"
                  }
                },
                {
                  "report_date": "2020-08-03T00:00:00Z",
                  "source": "https://actionability.clinicalgenome.org/ac/Pediatric/ui/stg2SummaryRpt?doc=AC065",
                  **"attributed_to": null,**
                  "classification": {
                    "label": "Assertion Pending",
                    "curie": "SEPIO:0003541"
                  }
                },
                {
                  "report_date": "2020-08-03T00:00:00Z",
                  "source": "https://actionability.clinicalgenome.org/ac/Adult/ui/stg2SummaryRpt?doc=AC057",
                  "attributed_to": {
                    "label": "Adult Actionability Working Group"
                  },
                  "classification": {
                    "label": "Assertion Pending",
                    "curie": "SEPIO:0003541"
                  }
                },
                {
                  "report_date": "2020-08-03T00:00:00Z",
                  "source": "https://actionability.clinicalgenome.org/ac/Pediatric/ui/stg2SummaryRpt?doc=AC057",
                  **"attributed_to": null,**
                  "classification": {
                    "label": "Assertion Pending",
                    "curie": "SEPIO:0003541"
                  }
                }
              ]
            },
            {
              "disease": {
                "label": "homozygous familial hypercholesterolemia",
                "curie": "MONDO:0018328"
              },
              "mode_of_inheritance": null,
              "actionability_assertions": [
                {
                  "report_date": "2020-08-03T00:00:00Z",
                  "source": "https://actionability.clinicalgenome.org/ac/Adult/ui/stg2SummaryRpt?doc=AC065",
                  "attributed_to": {
                    "label": "Adult Actionability Working Group"
                  },
                  "classification": {
                    "label": "Assertion Pending",
                    "curie": "SEPIO:0003541"
                  }
                },
                {
                  "report_date": "2020-08-03T00:00:00Z",
                  "source": "https://actionability.clinicalgenome.org/ac/Pediatric/ui/stg2SummaryRpt?doc=AC065",
                  **"attributed_to": null,**
                  "classification": {
                    "label": "Assertion Pending",
                    "curie": "SEPIO:0003541"
                  }
                }
              ]
            }
          ]
        },

**Comment by toneillbroad** [comment]
I cannot seem to reproduce this defect consistently now, as more data has been added to the production streams, the results of processing data version "2021-04-21T1250" up to the current record in the stream causes some actionability curations to be affected and others not - for example the one gene Phil pointed out "LDLR" is now working just fine.

I tried a number of ways of examining this but it exhibits heisenbug properties. I tried performing a graphql query of the "LDLR" gene after every new stream event was processed and displaying the topic and offset of each record along with the query output. But upon examining the results the "attributed_to" property was populated. I tried the same for other genes that were exhibiting the symptoms after processing all of the streams then restarting from data version "2021-04-21T1250" up to the current, but was never able to see the "attributed_to" property to be null.

Will put this on the back burner for now as Phil has implemented a work around. I will talk with Tristan more about this.

**Comment by larrybabb** [comment]
Yeah, i agree with your plan to put this on the back burner. Feel free to move this back to the Product or Sprint Backlog. I'm going to take the high priority off of this.

**Comment by toneillbroad** [comment]
Just a note that the genegraph data migration "2021-05-17T1615" seems to have cleared up the issue. Possibly caused by a race condition between startup of an older migration (possibly due to node migration) needing to process a lot of stream events while resolver cache warming scripts are running? But I'm a little skeptical of this explanation because it seemed that there were some Pediatric Working Groups returned from full query?
