### ISSUE TITLE
Link for old HNF1A curation does not redirect to latest curation in Genegraph

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#203]
see https://broadinstitute.atlassian.net/browse/CGWM-186.

[Here is the current URL](https://search.clinicalgenome.org/kb/gene-validity/CGGV:assertion_2f6d71c6-6595-49bf-a50e-fce726b22088-2018-10-05T160000.000Z) for the latest version of this GV assertion

The date on the end is off by 2 days. I presume this means it was updated and we’d like prior versions to all point to the latest version or we are overwriting prior versions with the latest version and then need to map ids from prior versions to the latest version.

**Comment by larrybabb** [comment]
@tnavatar or @toneillbroad please review this issue from the website team and provide some feedback on how we should proceed. Do not spend material time at this point please. Just a sense if this is a quick or not quick thing to address.

**Comment by KelseaChang5** [comment]
**Website Request points:**
[ ] - Estimated time based on quick review:
[ ] - Estimated priority level:
[ ] - Questions for Phil during next meeting:

**Comment by larrybabb** [comment]
@tnavatar will prioritize this to get it off our list. It will have a minor impact on his current GV work, but it is quicker then revisiting it time-to-time.

Solution: if the link fails, then we will get the latest version.

**Comment by toneillbroad** [comment]
Issue was an invalid regular expression.
