### ISSUE TITLE
Actionability report dates are getting modified by update dates rather than preserving the search date.

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#205]
see [CGWM-282](https://broadinstitute.atlassian.net/browse/CGWM-282)

This may be related to a formerly closed bug in the old Jira Clingen DX project [CDX-286](https://broadinstitute.atlassian.net/browse/CDX-286) which has a comment from @tnavatar that it was closed back in Oct 7 2020 when we were moving issues from Jira to Zenhub. 

Here's the request from Charisma

> We caught an issue with the report date on the website. If you look at SLC26A4 (AC1019), we have the updated date as 1/12/2021 and the search date as 8/18/2020. We want the search date to be displayed on the website, but the site is currently showing the updated date. NF2 has a similar issue (AC021).
> 
> The search date was added in a recent release of the website and I looked at quite a few records to ensure the correct date was displaying. I’m not sure if this was something I missed with that release or if something changed recently.
> 
> This is a high priority change to fix for actionability. We are going back and creating assertions for a lot of reports right now (which is reflected in the “updated date”, but not actually doing new literature searches or re-writing the reports. We feel that the “updated date” is really misleading and we know it causes confusion and extra feedback on the reports.
> 
> Thanks,Charisma

It would appear that the Updated Date coming over the stream for "updates" to previously approved reports should not be used as the "Reported Date".  Apparently Actionability works a bit differently than the VCI approval process whereby they can change previously approved reports without versioning them and re-approving them. They must have the need to make minor changes without concern for keeping an auditable historical copy of the previously published report. 

I might recommend making both the "update date" and "search date" available in graphql, then the downstream users (like the website) can determine what date to use for the version or report date or however they want to represent it.

I don't think graphql should be making decisions about what is or isn't a report date, we should probably be conveying the dates as they are represented in actionability and letting the users of the date render and represent it in whatever form they want now. This will give the users the ability to make changes without incurring technical debt on graphql to keep up with changing semantics by the data producers.

**Comment by larrybabb** [comment]
@toneillbroad for now let's see if we can feed the 'search-date' from actionability streams into the 'report-date' field in the graphql schema. And if we can let Scott know on how long this will take to deliver then he can convey that to Charisma.

**Comment by toneillbroad** [comment]
Super simple fix - just reverse the order of a date sort.

**Comment by toneillbroad** [comment]
Further testing revealed that the issue is still not fixed. Working on it again.

**Comment by toneillbroad** [comment]
After some conversation with Scott for clarification after I realized the "report_date" being returned from GraphQL on Actionability curations is in fact correct, he went back to check with Charisma. 

Here is the latest: 
Hey Terry!  I heard back from Charisma that she made a mistake and jumped the gun.  She apologized for the fire-drill.  I did ask her to thoroughly review the dates and I haven't heard back.  My guess is you can close the ticket on your side but I'll leave mine open as a reminder to check back with her next week.  Thanks again!

Closing ticket.
