### ISSUE TITLE
PRIORITY:  Can no longer query disease activity after 5/17 update to production

### ISSUE THREAD

**Issue by plweller3** [clingen-data-model/genegraph#207]
There seems to be a problem with the new load.  This query is no longer working, and as a result, stats, follow-genes, and even some of the web-site content is in an incomplete step.  Can we roll back production ASAP until this gets straightened out?  Then, it might not be a bad idea to revisit the QA process for releasing to production given the past two weeks.
7:36
{
  diseases(limit: null, curation_activity: ALL, sort: {field: GENE_LABEL, direction: ASC}) {
    count
    disease_list {
      label
      curie
      description
      synonyms
      last_curated_date
      curation_activities
    }
  }
}

The result of the above query is a return set of null.

{
  “data”: {
    “diseases”: {
      “count”: 1504,
      “disease_list”: null
    }
  }
}

**Comment by KelseaChang5** [comment]
December 7th 2021 Triage: Closed - Resolved by removing sort criteria from query
