### ISSUE TITLE
GeneGraph Statistics specification and review with stakeholders

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#214]
There have been several comments made by the website team (and stakeholders) that suggest there are "discrepancies in the stats" displayed on the website. It is unclear if these are misunderstandings, persistent issues, things that are being worked around or real problems. 

It is likely a combination of things. Nevertheless, the genegraph team should clearly document the specifications behind how statistics are being generated so that the stakeholders (and website devs) have a clear understanding.

Once we have the genegraph team on the same page with what and how the stats are working we should then setup a time to review and discuss with the stakeholders to see if there are any concerns or changes that are required to bring things together so that all players are on the same page.

This should help us understand and allow the stakeholders to more accurately assess if/when they see issues with the statistics rather than just feeling as if they "think" somethings wrong based on a misconception of how the stats are being generated.

**Comment by larrybabb** [comment]
This is based on report and ticket on the CGWM jira board https://broadinstitute.atlassian.net/browse/CGWM-248.

**Comment by KelseaChang5** [comment]
December 2021 triage: Closed
