### ISSUE TITLE
Implement new migration strategy utilizing storage buckets due to base data download caps

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#225]
After renewing the OMIM license, testing coding changes to the migration (#209), and troubleshooting base data URL changes (#222) - multiple runs of the data migration revealed that OMIM ha a data download cap in place. Tristan has had the idea of using base data downloaded (and periodically refreshed) from interwebz into a Google Cloud Storage Bucket. The migration would then use that data as it's data source thus limiting exposure to broken web links and data caps, which could potentially limit our ability to deploy new production code and migrations.

This is a place holder to discuss strategies.

**Comment by KelseaChang5** [comment]
December 2021 Triage: Closed
