### ISSUE TITLE
Removal request of TRX - X-linked intellectual disability-hypotonic face syndrome from GeneGraph

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#227]
Stakeholders have requested a Legacy curation (TRX - X-linked intellectual disability-hypotonic face syndrome) be removed. This curation was removed from the JSON. https://github.com/clingen-data-model/data-exchange-shared-json/commit/b1a6e8c4fe0a8be4fece512a12037de7cc895489

Please prioritize the refresh of GeneGraph once this is removed.

**Acceptance**
Curation for ATRX - X-linked intellectual disability-hypotonic face syndrome is removed from the website. https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_9511

@tnavatar or @toneillbroad Scott G has already removed the gene express record from the website's gene express json file.

Please update this and let Scott know when he can verify on Stage before deploying to Production.

see [CGWM-312](https://broadinstitute.atlassian.net/browse/CGWM-312?atlOrigin=eyJpIjoiZjdlNzk3OWQ0ZTEzNDE1Mzg4MjY2MmNmNmZmYmQxMDgiLCJwIjoiaiJ9) for original request.

**Comment by tnavatar** [comment]
Migration built and deployed to stage; will plan on migration to production 7/27 PM assuming all is well.

**Comment by larrybabb** [comment]
@tnavatar Did you expect this to go into production with the 7/27 release? Scott is looking for a status on this. I presume he's not seeing that it is gone or maybe he just needs me to affirm that it was done?

**Comment by tnavatar** [comment]
My apologies, I was intending to get it into production last night and it didn’t get out. Will take care of it tonight instead.

**Comment by tnavatar** [comment]
This is now updated in production
