### ISSUE TITLE
Prod Exception in resolver for `DosageAssertion/score': No matching clause: little evidence

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#228]
Phil Weller reported this on [slack back on Dec 02, 2020](https://clingen.slack.com/archives/GHEB7MZHQ/p1606927654005000). 

There's an outstanding issue [CGWM-89](https://broadinstitute.atlassian.net/browse/CGWM-89) in the Website team's Jira system that I dropped the ball on following up, but we need to get a status on where this issue stands and if an assessment on when we might be able to troubleshoot it and/or address it.

This is the query that returns the exception in GG production instance (https://genegraph-testing.clingen.app/ide)

```
{
  gene(iri: "HGNC:143") {
    label
    alternative_label
    hgnc_id
    chromosome_band
    curation_activities
    dosage_curation {
      curie
      report_date
      triplosensitivity_assertion {
        dosage_classification {
          ordinal
        }
        score
      }
      haploinsufficiency_assertion {
        dosage_classification {
          ordinal
        }
        score
      }
    }
  }
}
```

which returns 

```
{
  "errors": [
    {
      "message": "Exception in resolver for `DosageAssertion/score': No matching clause: little evidence",
      "extensions": {
        "field-name": "DosageAssertion/score",
        "arguments": null,
        "location": {
          "line": 21,
          "column": 9
        },
        "path": [
          "gene",
          "dosage_curation",
          "haploinsufficiency_assertion",
          "score"
        ]
      }
    }
  ]
}
```

**Comment by toneillbroad** [comment]
The issue here is that it appears for some Genes (ACTC1 in this example) the enumeration being passed from JIRA is "little evidence", but there is no path in the genegraph code to handle that enum. It is very easy to add the missing enum but coordination will be required with the UI for them being able to handle that enum on their side.

Here is the code with the current enums:

(case (str/lower-case classification)
      "no evidence" :NO_EVIDENCE
      "minimal evidence" :MINIMAL_EVIDENCE
      "moderate evidence" :MODERATE_EVIDENCE
      "sufficient evidence" :SUFFICIENT_EVIDENCE
      "gene associated with autosomal recessive phenotype" :ASSOCIATED_WITH_AUTOSOMAL_RECESSIVE_PHENOTYPE
      "dosage sensitivity unlikely" :DOSAGE_SENSITIVITY_UNLIKELY)))

The UI is passed the "NO_EVIDENCE" string for the score in some occasions, and must handle it on their side. We'll need to make sure we add "LITTLE_EVIDENCE" and they'll handle on their side.

**Comment by tnavatar** [comment]
At some point Phil must have changed the strings that were getting sent for this from JIRA. I wonder how far back this goes...

**Comment by larrybabb** [comment]
Thanks @toneillbroad I'll pass on your findings to @plweller3 to see what he wants to do.

**Comment by larrybabb** [comment]
Based on the reply from @plweller3 (below) it sounds like we should map LITTLE_EVIDENCE to MINIMAL_EVIDENCE. I presume these are aliases for the same scoring range? I'm not clear on whether this means we translate LITTLE_EVIDENCE to MINIMAL_EVIDENCE or somehow try to retain the different labels for the same ranges in the data? Since Phil is using the quantitative score it may not be a big deal but if the producer of the message is expecting the published message to retain the original text labels and aliases, then we may have a more complex concern. 

@toneillbroad let me know if you have a solution that you are confident to run with otherwise let's discuss with @tnavatar and/or phil/scott.

> I don’t recall exactly when Dosage published their preferred strings, but I’m guessing it was almost a year ago.  I know it was well before we went production.
> 
> The DCI does not send any of those strings.  Instead, it sends a numeric value for most of the items.  The exceptions being 30 and 40, which also include text for some historic reason.  It would seem that to avoid disruption and maintain backward compatibility, all you would need to do is add “little evidence” and map it also to MINIMAL_EVIDENCE with no other changes.  The fact that genegraph even sees “little evidence” leads me to believe that the importer into Kafka was likely changed a year ago, but genegraph was never updated to do anything with it.
> 
> Whatever you decide to do, note that I only use the ordinal value for the dosage_classification.  I don’t use the enumerated strings anymore.
> 
> Hope that helps.

**Comment by toneillbroad** [comment]
Mapped "little evidence" to :MINIMAL_EVIDENCE

Query result posted in the original comments now returns:
{
  "data": {
    "gene": {
      "label": "ACTC1",
      "alternative_label": "actin alpha cardiac muscle 1",
      "hgnc_id": "HGNC:143",
      "chromosome_band": "15q14",
      "curation_activities": [
        "ACTIONABILITY",
        "GENE_DOSAGE",
        "GENE_VALIDITY"
      ],
      "dosage_curation": {
        "curie": "CGDOSAGE:ISCA-7363-2017-06-01T08:56:54Z",
        "report_date": "2015-11-17T20:56:21Z",
        "triplosensitivity_assertion": {
          "dosage_classification": {
            "ordinal": 0
          },
          "score": "NO_EVIDENCE"
        },
        "haploinsufficiency_assertion": {
          "dosage_classification": {
            "ordinal": 1
          },
          "score": "MINIMAL_EVIDENCE"
        }
      }
    }
  }
}
