### ISSUE TITLE
Confusing ID numbers being seen in 2nd contributor GCI data

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#230]
From Scott on slack

> @Larry Babb @Tristan Nelson We are seeing GeneGraph return affiliation IDs that are 10000 number IDs was well as EPs with 40000 ID numbers (which the GCI team clarified were GCEP IDs).  The problem that has come up is now GeneGraph has a "Intellectual Disability and Autism" (10006) and also a "Intellectual Disability and Autism GCEP" (40006) EP group.  The 10006 has 151 curations where the 40006 has zero.  If needed we can hide the groups with zero curations.  I checked with Rao and curations won't be published from a 40000 GCEP ID.  I'm curious if this was introduced with the contributions work that was done, and GeneGraph must have released into production, maybe today?  When digging into GraphQL I see that curation (CGGV:assertion_c496551d-c7a7-4e49-ad41-8cfd49840dc1-2020-04-24T160000.000Z) has a contributor of CGAGENT:40025 (Long QT Syndrome GCEP)  as well as CGAGENT:10025 (Long QT Syndrome).  It looks that the process put in place for contributors is spawning the creation of additional EPs within GeneGraph which is spilling out into other areas.  Please advise.

**Comment by larrybabb** [comment]
@sgoehringer @larrybabb and @tnavatar met briefly to discuss concerns and confusion around the affiliation IDs in the secondary contributors section. Further analysis and discussion will need to take place with the GCI folks. 

For now the steps are to:
1. Roll back GeneGraph to before the secondary contributor addition was made which will reintroduce the TRX gene express record that was removed in the last release
2. Reapply the removal and build of GG to re-remove the TRX gene express record in a timely manner.

See ? for the follow up to getting secondary contributors representation in GG and the website in sync with how the GCI is managing and sharing that data.

**Comment by tnavatar** [comment]
Version of Genegraph in prod has been rolled back prior-to the addition of secondary contributors

**Comment by tnavatar** [comment]
The migration removing the relevant TRX curation has been deployed to prod.

**Comment by tnavatar** [comment]
PR #232 removed the secondary approver from the GCI data, which was the source of IDs in the 40k range. It's not very clear why this should be (it may be arbitrary), but removing this data from Genegraph should allow for the integration of the secondary approver data without this being an issue. According to our primary stakeholder for this (Erin), the secondary approver feature in the GCI is not useful to the curators or for the display of data at the present time, so this should be an appropriate resolution for this issue. That said, we really need to follow up at some point about what the requisite roles are, and whether credit should be assigned to the overall EP or the GCEP.

Will be deploying this update to stage for testing; if all goes well suggest closing this ticket and opening another for following up on the issue of clarifying with the Stanford folks and stakeholders who should get credit for what.
