### ISSUE TITLE
restrict graphIQL access to GeneGraphQL

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#235]

**Comment by KelseaChang5** [comment]
@tnavatar Are we definitely planning to do this within the next 6 months? Thanks!

**Comment by tnavatar** [comment]
No; I think it's unlikely we'll do this ever, TBH.

**Comment by KelseaChang5** [comment]
Thanks, will archive.

**Comment by larrybabb** [comment]
closing this.
