### ISSUE TITLE
Create GG Transformed Persistent Streams (clinvar only mvp)

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#238]
Build environment and services necessary to reliably build persistent output topics for all data being transformed and stored in our final version of GG based on the GraphQL published schemas. Assure no duplicate message generation occurs. All messages should be versioned in the event that changes to the transformers cause previously generated messages to change.

ClinVar will need the ability to create presistent file representations from these output streams reliably as well as handle changes to changed representations of previously generated messages over time.

-

**Comment by KelseaChang5** [comment]
December 2021 Triage: Closed
