### ISSUE TITLE
Some curation groups appearing with zero curations

### ISSUE THREAD

**Issue by tnavatar** [clingen-data-model/genegraph#266]
Ilumina, the Antibody Deficiences GCEP, and the Myriad Women's Health group all show up on the affiliations list with zero curations. I believe these groups should not appear on the list at all.

**Comment by KelseaChang5** [comment]
@tnavatar This ticket was missed during retreat review, can you direct as to where this should go? Thanks!

**Comment by tnavatar** [comment]
Closed—this one was addressed some time ago.
