### ISSUE TITLE
Produce histogram of CNV submissions over time

### ISSUE THREAD

**Issue by tnavatar** [clingen-data-model/genegraph#267]
Erin requested a histogram of submission dates for copy number variants in ClinVar. A rough definition will do (anything >1kb, copy number gain/loss, del or dup). We're looking to get a sense of whether many CNVs have been submitted in recent years.

**Comment by larrybabb** [comment]
see https://docs.google.com/spreadsheets/d/1jNQGYVOMmb9_vQU62PwNgGXM5bbgGM4Pkvrs2O_lWKI/edit#gid=725100451
