### ISSUE TITLE
Code for ClinvarCombiner VCV MVP Transformer

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#295]
The input for the public VCV stream will be the ClinVarCombiner kafka topic which is JSON data.

The output of the VCV public stream will be SEPIO JSON-LD.

There needs to be a new transformer in the transforming genegraph that takes JSON -> SEPIO rdf -> JSON-LD.

Note: not sure where the wrapper for identifying the add, update and delete type goes. A new interceptor or here?

**Comment by KelseaChang5** [comment]
December 7th 2021 Triage: Overlaps tickets for output and for vcv jsonld (epic 281) - Closed
