### ISSUE TITLE
Canonical variation descriptor to include spdi canonical variation

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#296]
Code needs to be created that calls into https://normalize.cancervariants.org/ to create a VRS representation of the variant.

Add to transforming genegraph interceptor chain.

- Incorporate the spdi normalized endpoint
- Add the canonical variation descriptor

DoD: produce a canonical variation stream of the ClinVar test set

**Comment by theferrit32** [comment]
Included in 796eef51abf5f840a494a3f0ea85a1b16b51ff25
