### ISSUE TITLE
GeneDosage count discrepancy between production genegraph and stage genegraph build

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#301]
Prod env: 
{:genegraph-response-cache "true", :genegraph-data-version "2021-08-25T1510", :dx-topics "actionability;gci-legacy;gene-dosage-jira", :graphql-logging-topic "genegraph_logs", :genegraph-validate-events false, :data-vol "/data//2021-08-25T1510", :genegraph-version "gcr.io/clingen-dx/genegraph:1fb6cf9f23d819ead4ac3f17beba1e5c481c6732", :genegraph-mode "production", :genegraph-bucket "genegraph-prod", :genegraph-gql-cache "true"}

Stage env:
{:genegraph-response-cache "true", :genegraph-data-version "2021-10-08T1200:57593c8bd8075c2ece85c0d5f377de707b141d89", :dx-topics "actionability;gci-legacy;gene-dosage-jira", :graphql-logging-topic nil, :genegraph-validate-events false, :data-vol "/data//2021-10-08T1200:57593c8bd8075c2ece85c0d5f377de707b141d89", :genegraph-version "gcr.io/clingen-stage/genegraph:57593c8bd8075c2ece85c0d5f377de707b141d89", :genegraph-mode "production", :genegraph-bucket "genegraph-stage", :genegraph-gql-cache "true"}

{
  genes(limit: null, curation_activity: GENE_DOSAGE) {
    count
  }
}

Prod count: 1475
Stage count:  1446
Difference: 29 missing from stage deployment

Missing IRIs:
http://dx.clinicalgenome.org/entities/ISCA-10681-2021-04-24T13:40:42Z
http://dx.clinicalgenome.org/entities/ISCA-11289-2021-06-09T19:21:58Z
http://dx.clinicalgenome.org/entities/ISCA-12789-2020-12-29T17:48:37Z
http://dx.clinicalgenome.org/entities/ISCA-13514-2021-07-19T14:35:31Z
http://dx.clinicalgenome.org/entities/ISCA-1421-2021-08-16T14:41:05Z
http://dx.clinicalgenome.org/entities/ISCA-1625-2021-08-19T19:51:06Z
http://dx.clinicalgenome.org/entities/ISCA-18075-2021-07-19T14:35:59Z
http://dx.clinicalgenome.org/entities/ISCA-1869-2021-04-14T16:25:58Z
http://dx.clinicalgenome.org/entities/ISCA-20454-2021-02-08T14:11:30Z
http://dx.clinicalgenome.org/entities/ISCA-21217-2021-04-14T16:27:42Z
http://dx.clinicalgenome.org/entities/ISCA-21830-2021-08-02T14:27:53Z
http://dx.clinicalgenome.org/entities/ISCA-24399-2020-12-09T20:02:08Z
http://dx.clinicalgenome.org/entities/ISCA-25281-2020-11-24T15:01:53Z
http://dx.clinicalgenome.org/entities/ISCA-25535-2021-08-02T15:55:15Z
http://dx.clinicalgenome.org/entities/ISCA-2743-2021-05-13T17:50:40Z
http://dx.clinicalgenome.org/entities/ISCA-29983-2021-06-09T19:23:35Z
http://dx.clinicalgenome.org/entities/ISCA-31161-2020-12-30T14:19:37Z
http://dx.clinicalgenome.org/entities/ISCA-31361-2021-04-14T16:25:36Z
http://dx.clinicalgenome.org/entities/ISCA-32810-2021-09-12T12:12:44Z
http://dx.clinicalgenome.org/entities/ISCA-34702-2021-06-29T17:16:54Z
http://dx.clinicalgenome.org/entities/ISCA-35336-2021-08-16T14:41:16Z
http://dx.clinicalgenome.org/entities/ISCA-35648-2018-10-16T16:01:25Z
http://dx.clinicalgenome.org/entities/ISCA-36990-2021-05-13T17:51:57Z
http://dx.clinicalgenome.org/entities/ISCA-3923-2021-05-20T19:33:07Z
http://dx.clinicalgenome.org/entities/ISCA-3940-2021-06-11T13:25:14Z
http://dx.clinicalgenome.org/entities/ISCA-5418-2021-04-08T14:39:58Z
http://dx.clinicalgenome.org/entities/ISCA-8398-2021-07-26T19:18:31Z
http://dx.clinicalgenome.org/entities/ISCA-8684-2021-05-13T17:48:53Z
http://dx.clinicalgenome.org/entities/ISCA-9293-2021-06-18T19:35:08Z

**Comment by KelseaChang5** [comment]
December 2021 Triage: Closed
