### ISSUE TITLE
Add default score to evidence line

### ISSUE THREAD

**Issue by tnavatar** [clingen-data-model/genegraph#365]
Need to display the default score for given evidence lines, when available. this is generally present under the 'calculatedScore' field.

**Comment by larrybabb** [comment]
@tnavatar are you waiting on someone else to review this? if so, can you assign or call them out in a comment or create a PR for them to review?

**Comment by tnavatar** [comment]
Could probably close this one (and many others that I had put in 'review')

**Comment by larrybabb** [comment]
go for it. If you want someone else to review and close, please reassign. no pressure. but... it's really nice and fun to close things. so i hear.
