### ISSUE TITLE
Validate curations present in old data and not in new

### ISSUE THREAD

**Issue by tnavatar** [clingen-data-model/genegraph#371]
One curation (MYBPC3 - DCM) [652d0370-9574-450c-b7c4-eec86ade9046] has been identified as not being present anywhere in the gene-validity-raw stream or in the batch data provided earlier. Once we have validated the set of curations not available in the new data sources, we can report back to the Stanford folks and construct a plan for making this data available.

The following is the set of curations available on prod and not gv-dev. Note that some of these may be present and not imported due to an error on our side, hence the required validation.

#{"8afc42b0-6c5e-460b-87d1-035c051fe7ca"
  "2beee8a9-193c-41ca-92c4-484c8e034b02"
  "215f3113-cfb6-44cc-a68b-1eb6539c9fa0"
  "8f241e6c-2fc8-4f23-b976-3b79d90fad3e"
  "1ec53217-814e-44b3-a7b7-0f18311c20f3"
  "3b7c89d4-ccb2-4d4e-ad11-9d6051a40b6d"
  "aef9a60b-a94f-4318-824e-e748c5c20ecb"
  "746b46e8-0621-4879-80a1-4fb1679975be"
  "3f91c5fe-8e58-4c98-9878-e428e2e41dd7"
  "2e02ec85-306f-4465-b8f9-a6eb7e4e8056"
  "d74395ba-66ee-43c6-8d3c-c353bd8e5e82"
  "3e123751-078a-4d30-9f83-847119982342"
  "c6bc94e9-cdf2-4efb-b654-004541efc344"
  "132fafbf-bb34-447c-9f6a-65803679eeb8"
  "5fad1866-75ce-470f-984c-e64bb7e11168"
  "49e794f4-8725-4499-a0a2-82591b42cab5"
  "5a617cb4-94ec-4f34-b97e-10d9808a1581"
  "94042756-2e7a-4cfa-812c-1b88b703eeea"
  "652d0370-9574-450c-b7c4-eec86ade9046"
  "afba0573-9f47-4814-bf3a-ef41f5512dee"
  "2c48d88b-d100-4203-8abf-03f3199bf3e0"
  "f970ced6-0164-41ed-9e1f-1fb9f892bca6"
  "dcea255c-11e4-46fd-b0f7-2de68311a75c"
  "fb987774-0e5b-4466-924f-6f19fccc6599"
  "5af80ea6-31c6-47d2-a5a5-299380f5593c"
  "194f9130-2529-4016-a689-47ec259f941c"
  "afe2baae-73d8-4f77-a106-a9163dbde4ce"
  "130ca053-9f40-4fd5-b89c-b9b374694fda"
  "13027de9-c84a-4968-936b-6356265193a6"}

**Comment by dazzariti** [comment]
Next step: @tnavatar will set up a meeting with Kyle and Terry to orient them to the issue and steps that need to be taken so they can work on it when available

**Comment by tnavatar** [comment]
12 of these are not at all present in any of the new data we have available:

({:gene-iris ["https://www.ncbi.nlm.nih.gov/gene/87"],
  :disease-iris ["http://purl.obolibrary.org/obo/MONDO_0014078"],
  :moi-iris ["http://purl.obolibrary.org/obo/HP_0000006"],
  :agent-iris ["http://dataexchange.clinicalgenome.org/agent/10028"],
  :provisionalClassification "215f3113-cfb6-44cc-a68b-1eb6539c9fa0"}
 {:gene-iris ["https://www.ncbi.nlm.nih.gov/gene/27063"],
  :disease-iris ["http://purl.obolibrary.org/obo/MONDO_0005045"],
  :moi-iris ["http://purl.obolibrary.org/obo/HP_0000006"],
  :agent-iris ["http://dataexchange.clinicalgenome.org/agent/10008"],
  :provisionalClassification "8f241e6c-2fc8-4f23-b976-3b79d90fad3e"}
 {:gene-iris ["https://www.ncbi.nlm.nih.gov/gene/7273"],
  :disease-iris ["http://purl.obolibrary.org/obo/MONDO_0005021"],
  :moi-iris ["http://purl.obolibrary.org/obo/HP_0000006"],
  :agent-iris ["http://dataexchange.clinicalgenome.org/agent/10035"],
  :provisionalClassification "1ec53217-814e-44b3-a7b7-0f18311c20f3"}
 {:gene-iris ["https://www.ncbi.nlm.nih.gov/gene/1654"],
  :disease-iris ["http://purl.obolibrary.org/obo/MONDO_0020119"],
  :moi-iris ["http://purl.obolibrary.org/obo/HP_0001417"],
  :agent-iris ["http://dataexchange.clinicalgenome.org/agent/10006"],
  :provisionalClassification "3b7c89d4-ccb2-4d4e-ad11-9d6051a40b6d"}
 {:gene-iris ["https://www.ncbi.nlm.nih.gov/gene/1674"],
  :disease-iris ["http://purl.obolibrary.org/obo/MONDO_0016587"],
  :moi-iris ["http://purl.obolibrary.org/obo/HP_0000006"],
  :agent-iris ["http://dataexchange.clinicalgenome.org/agent/10003"],
  :provisionalClassification "aef9a60b-a94f-4318-824e-e748c5c20ecb"}
 {:gene-iris ["https://www.ncbi.nlm.nih.gov/gene/6949"],
  :disease-iris ["http://purl.obolibrary.org/obo/MONDO_0002457"],
  :moi-iris ["http://purl.obolibrary.org/obo/HP_0000006"],
  :agent-iris ["http://dataexchange.clinicalgenome.org/agent/10007"],
  :provisionalClassification "3f91c5fe-8e58-4c98-9878-e428e2e41dd7"}
 {:gene-iris ["https://www.ncbi.nlm.nih.gov/gene/282996"],
  :disease-iris ["http://purl.obolibrary.org/obo/MONDO_0005021"],
  :moi-iris ["http://purl.obolibrary.org/obo/HP_0000006"],
  :agent-iris ["http://dataexchange.clinicalgenome.org/agent/10035"],
  :provisionalClassification "3e123751-078a-4d30-9f83-847119982342"}
 {:gene-iris ["https://www.ncbi.nlm.nih.gov/gene/5053"],
  :disease-iris ["http://purl.obolibrary.org/obo/MONDO_0009861"],
  :moi-iris ["http://purl.obolibrary.org/obo/HP_0000007"],
  :agent-iris ["http://dataexchange.clinicalgenome.org/agent/10011"],
  :provisionalClassification "5a617cb4-94ec-4f34-b97e-10d9808a1581"}
 {:gene-iris ["https://www.ncbi.nlm.nih.gov/gene/8291"],
  :disease-iris ["http://purl.obolibrary.org/obo/MONDO_0015152"],
  :moi-iris ["http://purl.obolibrary.org/obo/HP_0000007"],
  :agent-iris ["http://dataexchange.clinicalgenome.org/agent/10061"],
  :provisionalClassification "94042756-2e7a-4cfa-812c-1b88b703eeea"}
 {:gene-iris ["https://www.ncbi.nlm.nih.gov/gene/4607"],
  :disease-iris ["http://purl.obolibrary.org/obo/MONDO_0005021"],
  :moi-iris ["http://purl.obolibrary.org/obo/HP_0000006"],
  :agent-iris ["http://dataexchange.clinicalgenome.org/agent/10035"],
  :provisionalClassification "652d0370-9574-450c-b7c4-eec86ade9046"}
 {:gene-iris ["https://www.ncbi.nlm.nih.gov/gene/415"],
  :disease-iris ["http://purl.obolibrary.org/obo/MONDO_0010555"],
  :moi-iris ["http://purl.obolibrary.org/obo/HP_0001417"],
  :agent-iris ["http://dataexchange.clinicalgenome.org/agent/10060"],
  :provisionalClassification "2c48d88b-d100-4203-8abf-03f3199bf3e0"}
 {:gene-iris ["https://www.ncbi.nlm.nih.gov/gene/7957"],
  :disease-iris ["http://purl.obolibrary.org/obo/MONDO_0009697"],
  :moi-iris ["http://purl.obolibrary.org/obo/HP_0000007"],
  :agent-iris ["http://dataexchange.clinicalgenome.org/agent/10005"],
  :provisionalClassification "f970ced6-0164-41ed-9e1f-1fb9f892bca6"})

Will report to Gloria and see what can be discovered.

**Comment by tnavatar** [comment]
Gloria suggested she would attempt to reproduce Rao's original batch process for these files on the gci-tech-talk channel on slack.

**Comment by tnavatar** [comment]
This leaves the following curations which appear to exist but are unprocessed:

(["8afc42b0-6c5e-460b-87d1-035c051fe7ca" 1 0]
 ["2beee8a9-193c-41ca-92c4-484c8e034b02" 1 0]
 ["746b46e8-0621-4879-80a1-4fb1679975be" 1 0]
 ["2e02ec85-306f-4465-b8f9-a6eb7e4e8056" 1 0]
 ["d74395ba-66ee-43c6-8d3c-c353bd8e5e82" 1 0]
 ["c6bc94e9-cdf2-4efb-b654-004541efc344" 1 0]
 ["132fafbf-bb34-447c-9f6a-65803679eeb8" 1 0]
 ["5fad1866-75ce-470f-984c-e64bb7e11168" 1 0]
 ["49e794f4-8725-4499-a0a2-82591b42cab5" 1 0]
 ["afba0573-9f47-4814-bf3a-ef41f5512dee" 1 0]
 ["dcea255c-11e4-46fd-b0f7-2de68311a75c" 1 0]
 ["fb987774-0e5b-4466-924f-6f19fccc6599" 1 0]
 ["5af80ea6-31c6-47d2-a5a5-299380f5593c" 1 0]
 ["194f9130-2529-4016-a689-47ec259f941c" 1 0]
 ["afe2baae-73d8-4f77-a106-a9163dbde4ce" 1 0]
 ["130ca053-9f40-4fd5-b89c-b9b374694fda" 1 0]
 ["13027de9-c84a-4968-936b-6356265193a6" 0 3])

**Comment by tnavatar** [comment]
The remaining should have been fixed with the last PR (#374) Provenance did not hang off the GDM for some older records

**Comment by tnavatar** [comment]
Gloria is putting together a package of the above, hopefully to be delivered next week.

**Comment by tnavatar** [comment]
Received package from Gloria (plus one more curation that had been updated), changes should currently be merged.
