### ISSUE TITLE
GC Express Request GitHub Template

### ISSUE THREAD

**Issue by KelseaChang5** [clingen-data-model/genegraph#373]
**Goal:** To create a GiHub issue template with all pertinent information  for the Gene Curation Small Group so that they can just directly make GC Express requests to us instead of having Phil make the ticket on his board and then transferring it to our board 

**DoD:** Publishing the template and informing the Gene Curation Small Group of this change/confirming with them that the template includes all relevant information that would need to be provided

Attached is the draft for the template:
![GC Express GitHub Issue Template v.1.png](https://images.zenhubusercontent.com/6189303ebad10a9727d59b63/edb22a4b-b094-48a1-9b68-edb574ee7a9a)

**Future Steps:** get steps needed to complete these requests from Terry or Tristan and automate it

**Comment by KelseaChang5** [comment]
[Link to template](https://github.com/clingen-data-model/genegraph/issues/new?assignees=&labels=genevalidity&template=gc-express-request.md&title=) in genegraph repo 

![GC Express GitHub Issue Template v.2.png](https://images.zenhubusercontent.com/6189303ebad10a9727d59b63/1cf9b951-0645-4d7b-9b45-68b27520f054)

**Comment by KelseaChang5** [comment]
@larrybabb Who is the point person from the gene curation group that I should send this template/change of request process to?

**Comment by larrybabb** [comment]
@KelseaChang5 I reviewed your template and converted it to a YAML format which allowed me to have better control over create the form fields to capture the attributes you identified. I committed the update gc_express_removal.yaml file and removed the existing markdown (.md) formatted files. Please check out the workflow and form itself [when selecting new issue on the genegraph repo](https://github.com/clingen-data-model/genegraph/issues/new/choose). If it looks good, please communicate the new workflow to the proper stakeholders (Phil and Erin will know, but I think Molly and Marina are two of them).

**Comment by larrybabb** [comment]
@KelseaChang5 btw I defaulted the assignment of these tickets to Terry O'Neill for now. If we find that's not a reasonable approach we can remove him from the template as the default. I also added a new "gcexpress" label to the repo to add to the genevalidity label which should help them stand out on the zenhub board.

**Comment by KelseaChang5** [comment]
Presented this process change during the **ClinGen Education, Coordination & Training WG** on January 26th. Also added a link to the ticket template on the [ClinGen Coordinator Resource](https://sites.google.com/broadinstitute.org/clinical-genome-resource/education-coordination-and-training-working-group/coordinator-resource) ClinGen google site. Will close.
