### ISSUE TITLE
Update JSON-LD writer to use prefix compacting

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/genegraph#378]
Compacting API (have not tested yet):
https://javadoc.io/doc/com.apicatalog/titanium-json-ld/latest/com/apicatalog/jsonld/JsonLd.html#compact(com.apicatalog.jsonld.document.Document,com.apicatalog.jsonld.document.Document)

One note here is that this issue: https://github.com/w3c/json-ld-syntax/issues/329 may be relevant and we may need to use an expanded form of the prefixes in the jsonld context which provide `@prefix: true` for each, to force the prefixes ending in `_` to be interpreted as desired. This is required on JSON-LD playground. Have not checked with Titanium library, but since these outputs are for public use it needs to be able to be interpreted consistently.

For example, with SEPIO:

```
{
  "@context": {
    "dc": "http://purl.org/dc/terms",
    "sepio": {
      "@id": "http://purl.obolibrary.org/obo/SEPIO_",
      "@prefix": true
    }
  }
}
```

**Comment by larrybabb** [comment]
@theferrit32 what state should this be in? Icebox, Backlog, Selected for Dev, ...?

**Comment by theferrit32** [comment]
Confirming that `titanium-json-ld` is compacting terms as desired. I am working on putting this into the jsonld message generation step. It would be nice to avoid needing to re-specify all the terms in a static context file. If the terms are defined in `property-names.edn` or an owl file that can be loaded with labeled properties, that would be preferable.

doc link: https://javadoc.io/doc/com.apicatalog/titanium-json-ld/latest/com/apicatalog/jsonld/api/CompactionApi.html
