### ISSUE TITLE
Expose the GDM UUID from the GCI in the genegraph gene_validity_assertions() call

### ISSUE THREAD

**Issue by KelseaChang5** [clingen-data-model/genegraph#382]
Website request (CGWM-364) - ClinGen Website JIRA Board ticket [link](https://broadinstitute.atlassian.net/jira/software/projects/CGWM/issues/CGWM-364)
**Requested:** January 14, 2022
**Requested Date of Completion:** January 28, 2022

**Description**
Currently, genegraph uses the GCI Record ID as it basis for its curie.  This is different from the Gene Tracker, which uses the GDM_UUID.   In order to correlate the two, genegraph needs to make available the attribute in the gene_validity_assertions() listing call.  Because genegraph manipulates the Record ID from the GCI, asking the Gene Tracker to include the ID in their information would not help.  

The GCI included the GDM_UUID in the message packet genegraph currently provides as legacy_json with the individual assertion calls, and while the website can extract this for use on the summary report, consuming this for each listing entry on other screens would result in an unreasonable response time.  The GCI made this change on their 1/13/2022 release to production

The exact request is:

gene_validity_assertions(...)
...
gdm_uuid
...
}

Note that the gdm_uuid must be EXACTLY as provided by the GCI and not manipulated in any way.

**Comment by KelseaChang5** [comment]
**Website Request Checklist:**
- [ ]  Estimated time based on quick review:
- [ ]  Estimated priority level: High per JIRA ticket
- [ ]  Questions for Phil during next meeting:

**Comment by tnavatar** [comment]
The information that Phil needs will be made available with the full GDV release. We may be able to make a small accommodation for him, but this probably ought to be considered a Won't Fix, since we should have this Information for him soon.

**Comment by KelseaChang5** [comment]
> The information that Phil needs will be made available with the full GDV release. We may be able to make a small accommodation for him, but this probably ought to be considered a Won't Fix, since we should have this Information for him soon.

Information relayed to Phil

**Comment by KelseaChang5** [comment]
@tnavatar Phil seems ok with this but with the following conditions:
- The full GDV in production by the 28th
- The gdm_uuid would be accessible through the gene_validity_assertions() call

**Comment by toneillbroad** [comment]
Agreed with Phil:
- report_id is the field to pull the gdm id from. 
- will keep the report_id field name in graphql to keep it consistent with the json field
