### ISSUE TITLE
Scored Genetic Evidence Questions

### ISSUE THREAD

**Issue by KelseaChang5** [clingen-data-model/genegraph#385]
**Question from Phil via email:**

For the Scored Genetic Evidence section of the new rich data, can you confirm that the following table fields will unsupported in the initial release?
- Proband Sex
- Proband Age
- Proband Ethnicity
- Proband Phenotypes
- Proband Previous Testing
- Proband Methods of Detection
- De Novo
- Score Status
- Proband Points (default points)
- Proband Counted Points
- Explanation

I can line up the rest of the columns with fields from the return data structure, but those seem to be missing all null.

Also, more a modeling question, but will an individual piece of variant evidence ever have more than one Variant Evidence structure and one Generic Resource structure? 
- If so, under what conditions?
- And if not, can we change this so it’s a more accessible attribute rather than disparate items in an array?

**Comment by larrybabb** [comment]
actually. added @KelseaChang5 and myself as well. This way we are sure to have this covered.

**Comment by tnavatar** [comment]
The scope for the initial release was based around the subset of the table fields felt essential for capturing the evidence, score, and the reason for the scoring, as discussed with Erin at this point at least a couple years ago.

The following fields were not part of that initial set, but it would be no difficulty to include them:

Proband Sex
Proband Age
Proband Ethnicity
Proband Phenotypes
Proband Previous Testing
Proband Methods of Detection

The remaining fields require a different explanation
De Novo -- not currently captured explicitly, though may be inferred through the type of the evidence line. This is easy and appropriate to include as an explicit field 

Score Status -- To my knowldedge the only score status that should be included in a published curation is 'score', therefore this is not included.

Proband Points (default points) -- Including the default points is an active request we are working on fulfilling

Proband Counted Points -- This is captured in the score of the evidence line

Explanation -- This is caputred in the description of the evidence line

**Comment by tnavatar** [comment]
Also, I'm not sure I understand the modeling question. @toneillbroad , if you're willing, could you get a concrete example from Phil about what he means?

**Comment by KelseaChang5** [comment]
@toneillbroad Not sure if you got a chance to ask Phil, but I emailed Phil the response to his first question and asked him to expand on his second question. Will keep this ticket open until we answer his second question
