### ISSUE TITLE
One duplicate, one missing model systems entry for RGS9

### ISSUE THREAD

**Issue by tnavatar** [clingen-data-model/genegraph#387]
Per Erin:

This entry has two separate model systems entries, each with the same label and score, but they should be coming from two different papers (Kuburas and Chen). GeneGraph is showing the Kuburas entry twice.

**Comment by larrybabb** [comment]
@tnavatar I'm moving this to the Backlog. Please change if it should be prioritized other than that.

**Comment by tnavatar** [comment]
seems to be resolved with current releases
