### ISSUE TITLE
GV assertion URL mismatch

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#395]
ops-u41 question from Phil:

is the gene_validity_assertion() call not available in genegraph-gvdev.clingen.app?

Also, I am trying to use the ID  from the screenshots for ERBB4 - CGGV:c28a8d2b-91dc-47b4-9b6c-daebe6057d56 - but that doesn’t match any gene-validity assertion for ERBB4.  The only one for ERBB4 is CGGV:assertion_fdd26ab6-0c1f-4322-9f70-cad651bb789f-2021-09-30T143144.993Z, but that doesn’t work against the resource() query.  There would seem to be a mismatch between what genegraph provides for listings and what the new stuff needs for its query.

**Comment by larrybabb** [comment]
@toneillbroad I'm assuming that since you assigned this question to @tnavatar from Phil that you need an answer promptly.

@tnavatar is there a "quick" answer to the questions above. If not can you provide any direction or information on how big an effort this will be to answer.

**Comment by toneillbroad** [comment]
Classifying the first part of this as a defect: the gene_validity_assertion() call is there, but it does not work with current gene_validity_raw iri's.

http://dataexchange.clinicalgenome.org/gci/6aa2b4ab-a58e-43cf-a9f5-c7a9b1655e39 appears to be a valid gene_validity_raw iri, but the query still returns null.

**Comment by toneillbroad** [comment]
Not a bug. Tristan set me straight. IRIs/Curies have changed. I'll work with Phil to see where he's getting his info from and perhaps show him where to get some of the gv assertions now.

**Comment by toneillbroad** [comment]
Bookmarks and links and follow me will be irreperably broken.

**Comment by toneillbroad** [comment]
Spoke with Tristan on this and we agreed to provide backward compatibility of gene validity assertion UUIDs similar to what has been done in the past with the gene_validity_assertion(iri:) graphql query.

**Comment by tnavatar** [comment]
This one feels like a critical issue for us to move to a more advanced testing stage. Will take this one over as Terry is on vacation.

**Comment by tnavatar** [comment]
This issue is gating for us to move forward with releasing the gene-validity-raw topic to prod, but does not result in user-visible changes. Am thinking this sits outside the next-user-testing milestone.
