### ISSUE TITLE
Add proband/patient for SOPv8 curations to link heterozygous variation

### ISSUE THREAD

**Issue by tnavatar** [clingen-data-model/genegraph#417]
The variant evidence item for SOPv8 curations represents the presence of a variant in a proband. In the case of AR curations with heterozygous variation, the two variants are scored independently and are linked via a patient. We need to represent that patient explicitly.

**Comment by larrybabb** [comment]
@tnavatar This seems big. Can we discuss at Monday's standup and determine if this is a must do and whether it stays in the backlog or somewhere else.
