### ISSUE TITLE
Genegraph sending the wrong dosage loss disease for gene EBP

### ISSUE THREAD

**Issue by KelseaChang5** [clingen-data-model/genegraph#455]
**Website request** (CGWM-376) - ClinGen Website JIRA Board ticket [link](https://broadinstitute.atlassian.net/browse/CGWM-376)
**Requested:** March 01, 2022

**Description:**
Back on January 5th, the haploinsufficiency disease was changed from MONDO:0026782 to MONDO:0020603.  A primary reason for this change was because MONDO:0026782 is an obsoleted term.

However, genegraph is still sending the loss disease as MONDO:0026782.  This is easily confirmed via graphiql:

{
"data": {
"gene": {
"hgnc_id": "HGNC:3133",
"label": "EBP",
"curation_activities": [
"GENE_DOSAGE"
],
"dosage_curation": {
"haploinsufficiency_assertion": {
"disease": {
"curie": "MONDO:0026782"
},
"dosage_classification": {
"label": "sufficient evidence",
"ordinal": 3,
"enum_value": "SUFFICIENT_EVIDENCE"
}
},
"triplosensitivity_assertion": {
"dosage_classification": {
"label": "no evidence",
"ordinal": 0,
"enum_value": "NO_EVIDENCE"
}
}
},
"genetic_conditions": [
{
"disease": {
"curie": "MONDO:0026782",
"label": "obsolete chondrodysplasia punctata 2, X-linked dominant"
},
"gene_validity_assertions": [],
"actionability_assertions": [],
"gene_dosage_assertions": [
{
"report_date": "2020-01-22T17:44:22Z",
"assertion_type": "HAPLOINSUFFICIENCY_ASSERTION",
"dosage_classification": {
"ordinal": 3
},
"curie": "CGDOSAGE:ISCA-4360x1-2021-12-18T14:46:22Z"
}
]
}
]
}
}
}

**Comment by tnavatar** [comment]
For some reason there are two different messages for this on the data exchange, one on 1/5, with the right MONDO term, the other on 1/19, with the older obsolete one. The DCI currently has the current correct one associated with the record.

https://dci.clinicalgenome.org/browse/ISCA-4360

Peculiar, perhaps bumping the record will fire off another (hopefully correct) message to the data exchange?

**Comment by tnavatar** [comment]
Forced a new message to come across the data exchange for this by deleting an extraneous space in one of the descriptions. That did the trick. Very unclear as to how an old version of the message came across after a newer version.
