### ISSUE TITLE
Update variation output serialization and validate with GA4GH VRS/VRSATILE schemas

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/genegraph#501]

**Comment by larrybabb** [comment]
@theferrit32 can you clarify in a comment (or the description above) what the end state is that we are looking to achieve and how it should be validated so that we can all understand what/who is needed to get this closed?

**Comment by theferrit32** [comment]
@larrybabb I think this should be closed and another ticket should be opened in the backlog for something like "Add realtime GA4GH variation schema validation". The purpose of that should be to do schema validation and error notification/annotation while the stream is being processed in order to let us know of any mismatches.
