### ISSUE TITLE
surface obvious build failures prior to PR merge

### ISSUE THREAD

**Issue by sjahl** [clingen-data-model/genegraph#532]
Right now, we only attempt docker builds on the master branch after merging PRs. I think this is the correct time to attempt a build that we're actually going to publish, but it makes it hard to see that you've broken something until after you merge the PR.

My feeling is that every commit on a PR should run some kind of unit/whatever tests that require enough genegraph execution to show that we can/can't produce a .jar

**Comment by theferrit32** [comment]
@larrybabb I think we should just go ahead and make a decision on these pull requests @sjahl created soon, like this week. I've added it to the Thursday dev agenda.
