### ISSUE TITLE
Case control table missing "Disease (Case)" field

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#546]
Case control table missing "Disease (Case)" field

**Comment by toneillbroad** [comment]
Gloria Cheung from Stanford has stated that these fields are not currently being populated in GCI due to an error.

**Comment by tnavatar** [comment]
Are we waiting on Gloria to fix this issue? Do we know if this is required to release things on our side?

**Comment by toneillbroad** [comment]
It appears that this field is now being populated in the GCI. Look at the case control field here https://curation.clinicalgenome.org/curation-central/9cd995dd-6940-409b-8408-0f6849881d25/gene-disease-evidence-summary/?snapshot=35d98673-d29e-43b4-9523-57b4c39707f7&status=Approved&affiliationId=10025
