### ISSUE TITLE
Need ACI condition name added to actionability_assertions

### ISSUE THREAD

**Issue by KelseaChang5** [clingen-data-model/genegraph#548]
Website request (CGWM-389) - ClinGen Website JIRA Board ticket [link](https://broadinstitute.atlassian.net/browse/CGWM-389)

**Description**
There is currently one, and eventually will be other, cases where multiple report pairs are associated with the same gene-mondo ID.  The only thing that really differentiates the multiple pairs is what the ACI adds as the condition name.  This name does not necessarily match MONDO’s name

Unfortunately, actionability_assertions() does not allow adding the disease{} construct.  So what we need is for genegraph to store actionability’s condition name for each assertion, and make it available via graphql.  For example:

genetic_conditions {
     disease {
          curie
         label
     }

     actionability_assertions {
          report_date
          source

         disease {

               curie

               label

         }
          attributed_to {
              label
         }
         classification {
                label
         }

     }
}

**Comment by larrybabb** [comment]
@tnavatar & @toneillbroad Phil is stating this is somewhat of a high priority. Can one of you triage this to see what would be involved and determine if this is a small, medium or large effort?  If its simple it would be great to get it done as soon as possible. However, if it is a bigger deal I can provide push back to determine how important this really is in comparison to other priorities.

**Comment by tnavatar** [comment]
Observations on this so far:
* The original disease name is not provided in the data being sent from the ACI.
* The *title* of the report is provided, which includes the disease name as listed in the ACI, in free text, as well as the list of genes included in the report. Note that this title covers the entire report, and not the diseases included in individual gene-disease pairs in the report, it really is less the 'original disease name' and more the actual title of the report. Nevertheless, it would be reasonable for us to provide this to Phil as the label of the report, and he can do with it what he will.
* There appear to be some issues with the way these curations were defined, data-wise:
  * They are both listed as co-dominant MOI on the report, however one report is really for the AR form (AC065) and one is for the AD form (AC057). That said, the MOI is not offered in the data being sent to us regardless.
  * They are both linked to the condition(s) for AD hypercholesterolemia . The AR forms (AC065) are additionally linked against the condition for AR hypercholesterolemia.
  * Genegraph is correctly offering both reports to the website. The website is programmed to display only one.

**Comment by tnavatar** [comment]
It appears that there are some issues with Phil's request once evaluated against the issue being reported by the stakeholder. I will plan to touch base with Charisma to discuss possible solutions.

**Comment by tnavatar** [comment]
Phil claims he can work with the report label to address the immediate stakeholder concern. Its certainly no trouble to offer this; have submitted a PR to this effect. Have suggested to stakeholders that including the MOI with the curation and normalizing against HPO terms would help in cases like this. If and when they do, we will have another task to ingest this.
