### ISSUE TITLE
SMARCA1/Coffin-Siris syndrome

### ISSUE THREAD

**Issue by tibingaman** [clingen-data-model/genegraph#611]
### Requester Name

Taylor Bingaman

### Requester Contact Info

tibingaman@geisinger.edu

### GC Express Entry Website URL

https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_5479

**Comment by larrybabb** [comment]
@toneillbroad or @tnavatar this is a gcexpress request directly from the end user. I'm just bringing it to your attention so that we can turn it around within a couple business days.
