### ISSUE TITLE
Determine if Clinvar Allele ID is available to display as link in Gene Disease Validity

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#616]
Courtney requested a link to Clinvar Allele Registry via CAID within GDV screens. She claimed that it is being entered into GCI curations. Need to determine if the GCI is passing this or if it is otherwise available in Genegraph for display as a link.

**Comment by tnavatar** [comment]
Closing; to the extent possible, CAIDs are being passed through.
