### ISSUE TITLE
Evaluate proper resolution of GCI score cap calculation to match that of genegraph

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#618]
Score caps apply to autosomal recessive and semi-dominant curations in the gci.
The calculation that the GCI applies is incorrect.
Whatever the calculation the GCI applies, genegraph must match and display.
Need to determine which calculation is being applied and have genegraph match.

**Comment by tnavatar** [comment]
Re-implementing a bug in the GCI that was fixed feels like it will make for hard to maintain code. Am going to hold off on implementing this until we can have a follow-up discussion with Erin.

**Comment by tnavatar** [comment]
The GCI has fixed this bug; closing this issue as Genegraph now reflects the GCI
