### ISSUE TITLE
Old disease names showing up on the website

### ISSUE THREAD

**Issue by hdziadzio** [clingen-data-model/genegraph#622]
https://broadinstitute.atlassian.net/browse/CGWM-395

Hi Phil,

Jenny Goldstein has reported that three GDMs she published on July 13th don't have the correct MONDO disease term on the website. Details of the 3 genes are shown below. One thing of note is that all 3 recently had their name changed, so the MONDO ID would be same but the associated name is different. In each case the new name was published but the old name appears on the website:

 

MMAA- methylmalonic aciduria, cblA type

 

GDM: https://curation.clinicalgenome.org/curation-central/9ac9942a-8b18-4f63-8842-4d742d92a429

Published GDM: https://search.clinicalgenome.org/kb/gene-validity/CGGV:assertion_5b81bb9e-5f71-47bf-b187-5eef83d91d57--2022-07-13T16:00:00

Date Published: 2022 Jul 13, 10:19 am

MMAB- methylmalonic aciduria, cblB type

GDM: https://curation.clinicalgenome.org/provisional-curation/e96c2942-3a0b-4b37-990f-210fbe399fb1

Published GDM: https://search.clinicalgenome.org/kb/gene-validity/CGGV:assertion_52b61ff5-afba-4ff7-adbc-51de6a837db7

Date Published: 2022 Jul 13, 10:40 am

 

RCBTB1- RCBTB1-related retinopathy

 

GDM: https://curation.clinicalgenome.org/curation-central/d7c72199-8738-4a9e-9c73-c21b26c0c9a6

Published GDM: https://search.clinicalgenome.org/kb/gene-validity/CGGV:assertion_f356649e-e6d6-4ab6-9e78-3774404794ff--2022-06-02T16:00:00

Date Published: 2022 Jul 13, 9:53 am

Cheers,

Matt

**Comment by hdziadzio** [comment]
Phil checked and confirmed that genegraph was returning the old names, not the new ones.

**Comment by tnavatar** [comment]
Ran new migration, promoted to production, validated fix with stakeholder.

**Comment by hdziadzio** [comment]
Hello all,

Thank you for the report; I’ve updated MONDO in Genegraph on our staging instance. These names appear to be correct through the stage version of the website:

https://search.clingen.info/kb/gene-validity/CGGV:assertion_5b81bb9e-5f71-47bf-b187-5eef83d91d57--2022-07-13T16:00:00
https://search.clingen.info/kb/gene-validity/CGGV:assertion_52b61ff5-afba-4ff7-adbc-51de6a837db7
https://search.clingen.info/kb/gene-validity/CGGV:assertion_f356649e-e6d6-4ab6-9e78-3774404794ff--2022-06-02T16:00:00

Please let me know if there are any obvious issues; I’ll promote this version to production tomorrow morning if everything looks OK.

—Tristan

**Comment by hdziadzio** [comment]
Hi Tristan,

This all looks good to me. Thanks so much!

Once in production, can we assume that previously published curations that may have had the same problem will be fixed automatically? Or will we have to republish them? 
Sorry - this is probably a daft question, but I just wanted to be sure that everything is updated appropriately on the website.

Thanks again for your help,

Jenny
