### ISSUE TITLE
[GC Express]:AFF2

### ISSUE THREAD

**Issue by jmsavatt** [clingen-data-model/genegraph#627]
### Requester Name

Juliann Savatt

### Requester Contact Info

jmsavatt@geisinger.edu

### GC Express Entry Website URL

https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_9508

### Additional Notes

This AFF2 Gene Express record needs to be removed from the ClinGen website. Thank you!

**Comment by tnavatar** [comment]
Removed from gc-express-json, currently building on stage.
