### ISSUE TITLE
[GC Express]: CGGCIEX:assertion_9593

### ISSUE THREAD

**Issue by RyanFWebb** [clingen-data-model/genegraph#628]
### Requester Name

Ryan Webb

### Requester Contact Info

rwebb@broadinstitute.org

### GC Express Entry Website URL

https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_9593

### Additional Notes

This is an old, out of date duplicate entry that the Hearing Loss GCEP would like removed. I am submitting on behalf of the GCEP per Marina DiStefano's request.

**Comment by tnavatar** [comment]
Removed from gciexpress and genegraph
