### ISSUE TITLE
[GC Express]:

### ISSUE THREAD

**Issue by jmsavatt** [clingen-data-model/genegraph#629]
### Requester Name

Juliann Savatt

### Requester Contact Info

jmsavatt@geisinger.edu

### GC Express Entry Website URL

https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_9554

### Additional Notes

Please remove the GeneExpress CREBBP curation.

**Comment by tnavatar** [comment]
Removed from GC Express JSON, will be removed on next Genegraph migration
