### ISSUE TITLE
Issue with Pulmonary Hypertension GCEP listing

### ISSUE THREAD

**Issue by hdziadzio** [clingen-data-model/genegraph#640]
Hi Phil and Tristan,

I wanted to forward along an issue that we are having on an update curation for ABCC8.

Previously this curation attributed the Pulmonary Hypertension GCEP as a secondary contributor. I updated the GCI record with a new provisional record yesterday, and removed the PH GCEP as a secondary contributor.  However, Carrie Welch, the PH GCEP coordinator, discovered the ABCC8 gene is still rendering on the PH GCEP gene list (See image below and this links)

Pulmonary Hypertension GCEP gene list on website: https://search.clinicalgenome.org/kb/affiliate/10071?page=1&size=25&search=

Note, ABCC8 shows as first gene on list and

ABCC8 curation website link: https://search.clinicalgenome.org/kb/genes/HGNC:59

Note, no secondary contributor on this page

Let me know if there is any other data you need, but I figured it may have been something on the website end for the sorting of genes to a particular GCEP that might not be updating.

 

Best,
Courtney

**Comment by hdziadzio** [comment]
From Phil: 

This is rather strange. 

First, it only happens on Prod.  Stage and even the GDV dev look fine.

Second, it only seems to show 9 curations when you query against the /graphql endpoint.  If you use the webtool graphiql, it shows 8.

Adding Terry for further investigation on the graphql side.

**Comment by tnavatar** [comment]
Addressed in #639

This is a fix for this issue, but we may need to consider another look at the caching strategy generally.

**Comment by tnavatar** [comment]
Moved into stage, will deploy to prod tomorrow if there are no issues with stage overnight.

**Comment by tnavatar** [comment]
Moved into stage, will deploy to prod tomorrow if there are no issues with stage overnight.
