### ISSUE TITLE
GDV testing part deux

### ISSUE THREAD

**Issue by tnavatar** [clingen-data-model/genegraph#642]

**Comment by larrybabb** [comment]
@toneillbroad I am under the impression that this epic is complete? If so, can you close out the remaining tasks. If however, the remaining tasks are being deferred or delayed, then let's create a new Epic in the backlog for "Open Gene Validity pipeline changes" (or something) and move the deferred items to that. What do you think?

**Comment by toneillbroad** [comment]
Closing per request of @larrybabb  
New GDV epic  #736 "Post release GDV pipeline"
