### ISSUE TITLE
Add the ability for a transformer to produce multiple named graphs

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/genegraph#655]
With the ClinVar data, and putting it into VRS/VRSATILE/SEPIO/VA schemas, we have a lot of cases where a sub-node is essentially an enum within a particular dataset. The Coding concepts in VRS, but perhaps other things too. It would be nice if these value objects which are referred to by many other objects could just be stored once.

They could be looked up during the transformation and referred to by messages after the first one that creates it, but this will unacceptably slow down the ingest time of large datasets. Even a few tens of milliseconds per message is probably too slow.

**Comment by theferrit32** [comment]
Attached is one example of a canonical variation object which has multiple versions, so the same exact VRS variation has been read into jena multiple times, within a named graph for each version. `q/ld1->` picks the first one, and it doesn't matter that it gets the right one because they all have the same values aside from the resource identifier (and graph name).

Example of one field being duplicated:
```json
{
    "vrs/end": [
        {
            "id": "d664ffb3e68b95f365cf0961dde151fc",
            "rdf/type": "https://vrs.ga4gh.org/terms/Number",
            "rdf/value": 80107580
        },
        {
            "id": "3edacf2ebd5895a99947f2bbac77e39e",
            "rdf/type": "https://vrs.ga4gh.org/terms/Number",
            "rdf/value": 80107580
        }
    ]
}
```

[test.txt](https://github.com/clingen-data-model/genegraph/files/9590125/test.txt)

**Comment by tnavatar** [comment]
This feature exists in Genegraph 2--though the group is using a different approach. Either way, closing.
