### ISSUE TITLE
Research and fix kafka disconnect issue

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#680]
Persistent issue with kafka disconnet causing stream offsets to be inconsistent and causing information being displayed on the website to be out of sync.

**Comment by larrybabb** [comment]
@toneillbroad FYI - i connected this issue to the PR that was in review so it automatically moved the issue from "Selected for Dev" to "Review".  If that's not correct, please let me know so I can undo my housekeeping efforts.

**Comment by toneillbroad** [comment]
While testing a local migration, there is a portion where the streams are shutdown in genegraph. This appeared to cause the new code I introduced to keep cycling with consumer reopens.
