### ISSUE TITLE
Craft documentation strategy for Graphql model and queries

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/genegraph#681]
Discussed the use of genegraph-ui (genegraph explorer) as a medium for documenting the graphql model exposed by genegraph to internal and external customers.

The goals are to have this documentation be comprehensive enough to expose the subtleties of our model. For example, in the gene disease validity model, autosomal recessive and semidominant curations have the genetic evidence represented by a proband score cap element, that has it's nested evidence the potentially multiple variant evidence that is encompassed by the score cap. SInce we are exposing this as a generic model, describing these structures to customers will be challenging.

Tutorials, in the case of gene disease validity, could take the form of an interactive notebook that describes the models with example queries and output.

**Comment by larrybabb** [comment]
@tnavatar we need to add this kind of documentation to our "internal" documentation structure as long as we have Phil using the gql api to access data from genegraph. Let's make sure to identify a place in our documentation for this so we can draft something asap.

**Comment by larrybabb** [comment]
@tnavatar you and I should review our tickets related to the documentation work we are doing to make sure all related tickets are refined and accurate. Let's take a few minutes tomorrow at the start of our time to do that.

**Comment by tnavatar** [comment]
Sounds good

**Comment by larrybabb** [comment]
@tnavatar suggest ice-box or archive for this until we can get back to seriously considering it. Your call

**Comment by tnavatar** [comment]
Closing obsolete issues.
