### ISSUE TITLE
Add object descriptors for clinical_assertion Statements

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/genegraph#690]
This will be to capture the disease/condition/phenotype name. The upstream field is `trait.name`.

If trivial to add, include the `trait.xrefs`, such as the OMIM id.

**Comment by larrybabb** [comment]
Here's a modified version of one of the gk-pilot scv records that I made to demonstrate some of the near future additions that will be needed, including `object_descriptor`, `agent.label`... It does not have the `local_key` in the extensions but that is also very much needed.
[ex1-varpath-clinvarscv.json.txt](https://github.com/clingen-data-model/genegraph/files/10135848/ex1-varpath-clinvarscv.json.txt)

**Comment by theferrit32** [comment]
@larrybabb I recall some discussion around whether we want to proceed with object descriptors being stored under a separate field from the objects, or whether they should be merged. Because of how I'm storing the traits right now it is easier to merge them so I will go ahead with that. But this will not validate with the currenet va-spec `Variant..Statement` schemas

**Comment by theferrit32** [comment]
Closed by #769
