### ISSUE TITLE
Add extensions for SCV Statements

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/genegraph#697]
Add every top-level `clinical_assertion` field not already included elsewhere in the object

**Comment by larrybabb** [comment]
For the initial release I really only need 'local_key'.

**Comment by theferrit32** [comment]
Implemented in branch: https://github.com/clingen-data-model/genegraph/commit/2c65f329fcf84501a11c070c5e4e50dd5b2d5799

Will submit PR with other changes to transformers, like object descriptor and submitter
