### ISSUE TITLE
Add ability to reference data version that is different from image version

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/genegraph#712]
1. Change the genegraph deployment yaml to use the `genegraph_data_version` helm value as the whole value of the `GENEGRAPH_DATA_VERSION` envvar.
2. Change the `.cloudbuild/*` files for genegraph that update values files in architecture to append `":$COMMIT_SHA"` to `genegraph_data_version`.

By setting the whole `GENEGRAPH_DATA_VERSION` based on a single value and not using the `genegraph_docker_image_tag` in it, instances of the chart can use a data migration created by a different version of the code than is being run. For example when wanting to deploy without running a migration, or when wanting to reference a static migration but update the code to a new version.

I currently do this by just commenting out the `:` and everything after on this line:
https://github.com/clingen-data-model/architecture/blob/0f57109e3d441ffb2272e1583710c604b15e9373/helm/charts/clingen-genegraph/templates/genegraph-deployment.yaml#L42

Note: Is a prereq for #521

**Comment by toneillbroad** [comment]
@theferrit32 Not sure I understand this. The only reason that the commit sha is appended to the genegraph_data_version is to now which commit was used to build it - and to potentially trace back to the changes in that commit. But there's no reason you can't reference a genegraph_data_version with a different commit sha so long as you know conceptually that the versions are compatible.
Maybe I'm just confused.

**Comment by theferrit32** [comment]
@toneillbroad The issue I'm running into is that the `GENEGRAPH_DATA_VERSION` envvar in the Deployment includes the same docker image tag that is being used to specify which version of the image the container is running. So the migration version that genegraph loads is tied to the image version being run. The migration file it will try to pull will have the code commit sha in the filename, but that file won't exist unless a migration is run first (or an old migration file is just copied to that new filename in the bucket). For some cases this is what we want, the migration version genegraph loads is based on the code version being run, but not always, like when we want to autodeploy a new code version but not run a migration.

Refactoring this so the `GENEGRAPH_DATA_VERSION` envvar doesn't depend on the `genegraph_docker_image_tag` helm value will make this easier.

**Comment by theferrit32** [comment]
### Proposed changes:
architecture:
https://github.com/clingen-data-model/architecture/pull/504/

genegraph:
https://github.com/clingen-data-model/genegraph/pull/714/

Example of the effect of the cloudbuild change in genegraph:
https://github.com/clingen-data-model/architecture/pull/503/files
