### ISSUE TITLE
[GC Express]: Removal of Colon Cancer GCEP SMAD4 GCEX record

### ISSUE THREAD

**Issue by courtneythaxton** [clingen-data-model/genegraph#722]
### Requester Name

Courtney Thaxton

### Requester Contact Info

courtney_thaxton@med.unc.edu

### GC Express Entry Website URL

https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_9856

### Additional Notes

I noticed that this colon cancer GCEP curation is a Gene Curation Express, and there is another curation for this gene by the hemostasis and thrombosis GCEP that curated for the syndrome including colon cancer.

You may want to check with the coordinators for the Hereditary Cancer GCEP Sheng-An and Deb Ritter just to confirm.

**Comment by dazzariti** [comment]
@toneillbroad I will talk with Courtney about this and confirm if she wants this removed or if she's flagged it for the GCEP to review.

**Comment by dazzariti** [comment]
@toneillbroad After reviewing with the relevant GCEPs, they do not wish to remove this Gene Curation Express curation at this time. I have asked them to submit a new ticket if they want to remove it in the future.

**Comment by toneillbroad** [comment]
Thank you Danielle!!!
