### ISSUE TITLE
GKPilot ClinVar SCV missing subject variation (externally reported)

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/genegraph#729]
@theferrit32 The Epic team noticed some missing subject variations in the gk pilot data.  I took a quic look and it seemed like a bug. Please let me know if what you find.

Here's the email I received....

> Mrinal Thomas (Epic) Jan 4, 2023 11:39a ET
> We noticed some of Germline Pathogenicity Statements point to a missing subject variation (cgterms:VariationDescriptor_7955.2022-06-26).

**Comment by theferrit32** [comment]
Should look at whether it's related to this: https://github.com/clingen-data-model/genegraph/issues/748

**Comment by theferrit32** [comment]
Running clinvar release 2023-04-10 through and will verify this variant is processed correctly.

**Comment by theferrit32** [comment]
Re-running 2023-04-10 release and will check the results for this record

**Comment by larrybabb** [comment]
@theferrit32 how's this coming along?
