### ISSUE TITLE
Genegraph should recover from no-internet connectivity at startup 

### ISSUE THREAD

**Issue by tnavatar** [clingen-data-model/genegraph#740]
Relevant thread in slack: https://clingen.slack.com/archives/C01S7GH0GJF/p1675709153213799

**Comment by larrybabb** [comment]
@tnavatar is this a concern? or should we icebox/archive/backlog or fix this?

**Comment by tnavatar** [comment]
Thanks for doing the review; I think will close for now, am expecting issues to be resolved in the next iteration of Genegraph.
