### ISSUE TITLE
[GC Express]: FTSJ1

### ISSUE THREAD

**Issue by icordovaG** [clingen-data-model/genegraph#751]
### Requester Name

Catalina Betancur

### Requester Contact Info

catalina.betancur@sorbonne-universite.fr

### GC Express Entry Website URL

https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_9515

### Additional Notes

FTSJ1 was recurated and we are waiting until the 2018 curation is removed to publish the new curation. 

Thank you for the help.

**Comment by toneillbroad** [comment]
Fix deployed on Wed Mar 1, 2023.
