### ISSUE TITLE
Merge main-repl functionality into main

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/genegraph#770]
I created main-repl separately in order to leave the existing `main.clj` completely untouched, and enable building the jar with `main/-main` as the executable entrypoint. But we currently build all the docker images with `main-repl/-main` as the entrypoint anyways, and the repl is disabled by default, enabled with an environment variable. A recent change to the snapshotting branch moves the repl server into its own namespace so it can be referred to outside the main namespace. So I think it would be better to merge the remaining `main_repl.clj` functionality into `main.clj` and get rid of the additional `build.clj` target so genegraph will always build the same jar that includes the ability to start a repl server.

**Comment by larrybabb** [comment]
@theferrit32 should we hold these in the "backlog"?
