### ISSUE TITLE
[GC Express]: 

### ISSUE THREAD

**Issue by courtneythaxton** [clingen-data-model/genegraph#780]
### Requester Name

Courtney Thaxton

### Requester Contact Info

courtney_thaxton@med.unc.edu

### GC Express Entry Website URL

https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_10077

### Additional Notes

Please remove as we have a duplicate record that is in the GCI.

Link for the GCEx removel is TTN with HCM: https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_10077

**Comment by toneillbroad** [comment]
Updated in stage and production

**Comment by courtneythaxton** [comment]
Thanks @toneillbroad !
