### ISSUE TITLE
[GC Express]: GC Express Removal

### ISSUE THREAD

**Issue by Sheng-An** [clingen-data-model/genegraph#786]
### Requester Name

Sheng-An Yang

### Requester Contact Info

Sheng-An.Yang@bcm.edu

### GC Express Entry Website URL

https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_3202

### Additional Notes

Please also remove:
https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_8432
https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_8502

Thank you!

**Comment by toneillbroad** [comment]
GC Express curations removed and verified.
